<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

/*
	ajax-callable script that returns code for either a combo drop-down or an auto-complete
	drop-down, based on number of items.

	REQUEST parameters:
	===============
	t: table name
	f: lookup field name
	id: selected id
	p: page number (default = 1)
	s: search term
	o: 0 (default) for text-only or 1 for full options list
	text: selected text
	filterer_[filterer]: name of filterer field to be used to filter the drop-down contents
				must be one of the filteres defined for the concerned field
*/

	$start_ts = microtime(true);

	// how many results to return per call, in case of json output
	$results_per_page = 50;

	$curr_dir = dirname(__FILE__);
	include("$curr_dir/defaultLang.php");
	include("$curr_dir/language.php");
	include("$curr_dir/lib.php");

	handle_maintenance();

	// drop-downs config
	$lookups = array(   
		'tb_vaga' => array(   
			'requerimento_id' => array(
				'parent_table' => 'tb_requerimento',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_requerimento`.`id`',
				'parent_from' => '`tb_requerimento` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_requerimento`.`recrutador_id` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_requerimento`.`empresa_id` LEFT JOIN `tb_contato` as tb_contato1 ON `tb_contato1`.`id`=`tb_requerimento`.`contato_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'empresa_id' => array(
				'parent_table' => 'tb_empresa',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_empresa`.`str_nome_fantasia`',
				'parent_from' => '`tb_empresa` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_empresa`.`str_responsavel` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_empresa`.`relacionamento_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'recrutador_id' => array(
				'parent_table' => 'tb_recrutador',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`tb_recrutador`.`str_nome`) || CHAR_LENGTH(`tb_recrutador`.`bol_comercial`), CONCAT_WS(\'\', `tb_recrutador`.`str_nome`, `tb_recrutador`.`bol_comercial`), \'\')',
				'parent_from' => '`tb_recrutador` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `tb_recrutador`.`id`, `tb_recrutador`.`str_nome` FROM `tb_recrutador` WHERE bol_recrutador = 1 AND bol_status = 1 ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'str_contratado_nome' => array(
				'parent_table' => 'tb_contratacao',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`tb_contratacao`.`str_candidato_nome`) || CHAR_LENGTH(`tb_contratacao`.`int_cpf`), CONCAT_WS(\'\', `tb_contratacao`.`str_candidato_nome`, \' - \', `tb_contratacao`.`int_cpf`), \'\')',
				'parent_from' => '`tb_contratacao` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'tb_entrevista' => array(   
			'empresa_id' => array(
				'parent_table' => 'tb_empresa',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_empresa`.`str_nome_fantasia`',
				'parent_from' => '`tb_empresa` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_empresa`.`str_responsavel` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_empresa`.`relacionamento_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'vaga_id' => array(
				'parent_table' => 'tb_vaga',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`tb_vaga`.`str_posicao`) || CHAR_LENGTH(`tb_vaga`.`str_alocacao`), CONCAT_WS(\'\', `tb_vaga`.`str_posicao`, \' - \', `tb_vaga`.`str_alocacao`), \'\')',
				'parent_from' => '`tb_vaga` LEFT JOIN `tb_requerimento` as tb_requerimento1 ON `tb_requerimento1`.`id`=`tb_vaga`.`requerimento_id` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_vaga`.`empresa_id` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_vaga`.`recrutador_id` LEFT JOIN `tb_contratacao` as tb_contratacao1 ON `tb_contratacao1`.`id`=`tb_vaga`.`str_contratado_nome` ',
				'filterers' => array('empresa_id' => 'empresa_id'),
				'custom_query' => 'SELECT `tb_vaga`.`id`, IF(CHAR_LENGTH(`tb_vaga`.`str_posicao`) || CHAR_LENGTH(`tb_vaga`.`str_alocacao`), CONCAT_WS(\'\', `tb_vaga`.`str_posicao`, \' - \', IF(    CHAR_LENGTH(`tb_alocacao1`.`str_nome`), CONCAT_WS(\'\',   `tb_alocacao1`.`str_nome`), \'\')), \'\') FROM `tb_vaga` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_vaga`.`empresa_id` LEFT JOIN `tb_alocacao` as tb_alocacao1 ON `tb_alocacao1`.`id`=`tb_vaga`.`str_alocacao` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_vaga`.`recrutador_id` WHERE dta_fechamento is null ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'recrutador_id' => array(
				'parent_table' => 'tb_recrutador',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_recrutador`.`str_nome`',
				'parent_from' => '`tb_recrutador` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `tb_recrutador`.`id`, `tb_recrutador`.`str_nome` FROM `tb_recrutador` WHERE bol_status = 1 ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			)
		),
		'tb_contratacao' => array(  
		),
		'tb_alocacao' => array(   
			'int_empresa' => array(
				'parent_table' => 'tb_empresa',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_empresa`.`str_nome_fantasia`',
				'parent_from' => '`tb_empresa` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_empresa`.`str_responsavel` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_empresa`.`relacionamento_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			)
		),
		'tb_recrutador' => array(  
		),
		'tb_empresa' => array(   
			'str_responsavel' => array(
				'parent_table' => 'tb_recrutador',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_recrutador`.`str_nome`',
				'parent_from' => '`tb_recrutador` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `tb_recrutador`.`id`, `tb_recrutador`.`str_nome` FROM `tb_recrutador` WHERE bol_comercial = 1 AND bol_status = 1 ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'relacionamento_id' => array(
				'parent_table' => 'tb_contato_tipo',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_contato_tipo`.`str_nome`',
				'parent_from' => '`tb_contato_tipo` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 2,
				'not_null' => true
			)
		),
		'tb_prova_tipo' => array(  
		),
		'tb_contato' => array(   
			'empresa_id' => array(
				'parent_table' => 'tb_empresa',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_empresa`.`str_nome_fantasia`',
				'parent_from' => '`tb_empresa` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_empresa`.`str_responsavel` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_empresa`.`relacionamento_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'tipo_id' => array(
				'parent_table' => 'tb_contato_tipo',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_contato_tipo`.`str_nome`',
				'parent_from' => '`tb_contato_tipo` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 2,
				'not_null' => true
			)
		),
		'tb_contato_tipo' => array(  
		),
		'tb_oportunidade' => array(   
			'tipo_id' => array(
				'parent_table' => 'tb_oportunidade_tipo',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_oportunidade_tipo`.`str_nome`',
				'parent_from' => '`tb_oportunidade_tipo` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'estagio_id' => array(
				'parent_table' => 'tb_oportunidade_estagio',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_oportunidade_estagio`.`str_nome`',
				'parent_from' => '`tb_oportunidade_estagio` LEFT JOIN `tb_oportunidade_tipo` as tb_oportunidade_tipo1 ON `tb_oportunidade_tipo1`.`id`=`tb_oportunidade_estagio`.`tipo_id` ',
				'filterers' => array('tipo_id' => 'tipo_id'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'empresa_id' => array(
				'parent_table' => 'tb_empresa',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_empresa`.`str_nome_fantasia`',
				'parent_from' => '`tb_empresa` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_empresa`.`str_responsavel` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_empresa`.`relacionamento_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'contato_id' => array(
				'parent_table' => 'tb_contato',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`tb_contato`.`str_primeiro_nome`) || CHAR_LENGTH(`tb_contato`.`empresa_id`), CONCAT_WS(\'\', `tb_contato`.`str_primeiro_nome`, \' - \', IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`), CONCAT_WS(\'\',   `tb_empresa1`.`str_nome_fantasia`), \'\')), \'\')',
				'parent_from' => '`tb_contato` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_contato`.`empresa_id` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_contato`.`tipo_id` ',
				'filterers' => array('empresa_id' => 'empresa_id'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			)
		),
		'tb_atendimento' => array(   
			'empresa_id' => array(
				'parent_table' => 'tb_empresa',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`tb_empresa`.`str_nome_fantasia`) || CHAR_LENGTH(`tb_empresa`.`id`), CONCAT_WS(\'\', `tb_empresa`.`str_nome_fantasia`, \' - ID \', `tb_empresa`.`id`), \'\')',
				'parent_from' => '`tb_empresa` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_empresa`.`str_responsavel` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_empresa`.`relacionamento_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'contato_id' => array(
				'parent_table' => 'tb_contato',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`tb_contato`.`str_primeiro_nome`) || CHAR_LENGTH(`tb_contato`.`str_sobrenome`), CONCAT_WS(\'\', `tb_contato`.`str_primeiro_nome`, \' \', `tb_contato`.`str_sobrenome`), \'\')',
				'parent_from' => '`tb_contato` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_contato`.`empresa_id` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_contato`.`tipo_id` ',
				'filterers' => array('empresa_id' => 'empresa_id'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'campanha_id' => array(
				'parent_table' => 'tb_campanha',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_campanha`.`str_nome`',
				'parent_from' => '`tb_campanha` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'usuario_id' => array(
				'parent_table' => 'tb_recrutador',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_recrutador`.`str_nome`',
				'parent_from' => '`tb_recrutador` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `tb_recrutador`.`id`, `tb_recrutador`.`str_nome` FROM `tb_recrutador` WHERE bol_comercial = 1 ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			)
		),
		'tb_oportunidade_tipo' => array(  
		),
		'tb_oportunidade_estagio' => array(   
			'tipo_id' => array(
				'parent_table' => 'tb_oportunidade_tipo',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_oportunidade_tipo`.`str_nome`',
				'parent_from' => '`tb_oportunidade_tipo` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			)
		),
		'tb_acompanhamento' => array(   
			'empresa_id' => array(
				'parent_table' => 'tb_empresa',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_empresa`.`str_nome_fantasia`',
				'parent_from' => '`tb_empresa` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_empresa`.`str_responsavel` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_empresa`.`relacionamento_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'contato_id' => array(
				'parent_table' => 'tb_contato',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`tb_contato`.`str_primeiro_nome`) || CHAR_LENGTH(`tb_contato`.`str_sobrenome`), CONCAT_WS(\'\', `tb_contato`.`str_primeiro_nome`, \' \', `tb_contato`.`str_sobrenome`), \'\')',
				'parent_from' => '`tb_contato` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_contato`.`empresa_id` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_contato`.`tipo_id` ',
				'filterers' => array('empresa_id' => 'empresa_id'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'contrato_id' => array(
				'parent_table' => 'tb_contrato',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_contrato`.`str_nome`',
				'parent_from' => '`tb_contrato` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_contrato`.`empresa_id` ',
				'filterers' => array('empresa_id' => 'empresa_id'),
				'custom_query' => 'SELECT `tb_contrato`.`id`, `tb_contrato`.`str_nome` FROM `tb_contrato` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_contrato`.`empresa_id` WHERE bol_status = 1 ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'usuario_id' => array(
				'parent_table' => 'tb_recrutador',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_recrutador`.`str_nome`',
				'parent_from' => '`tb_recrutador` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `tb_recrutador`.`id`, `tb_recrutador`.`str_nome` FROM `tb_recrutador` WHERE bol_comercial = 1 AND bol_status = 1 ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			)
		),
		'tb_contrato' => array(   
			'empresa_id' => array(
				'parent_table' => 'tb_empresa',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_empresa`.`str_nome_fantasia`',
				'parent_from' => '`tb_empresa` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_empresa`.`str_responsavel` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_empresa`.`relacionamento_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			)
		),
		'tb_campanha' => array(  
		),
		'tb_campanha_contato' => array(   
			'campanha_id' => array(
				'parent_table' => 'tb_campanha',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_campanha`.`str_nome`',
				'parent_from' => '`tb_campanha` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'empresa_id' => array(
				'parent_table' => 'tb_empresa',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_empresa`.`str_nome_fantasia`',
				'parent_from' => '`tb_empresa` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_empresa`.`str_responsavel` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_empresa`.`relacionamento_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'contato_id' => array(
				'parent_table' => 'tb_contato',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`tb_contato`.`str_primeiro_nome`) || CHAR_LENGTH(`tb_contato`.`str_sobrenome`), CONCAT_WS(\'\', `tb_contato`.`str_primeiro_nome`, \' \', `tb_contato`.`str_sobrenome`), \'\')',
				'parent_from' => '`tb_contato` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_contato`.`empresa_id` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_contato`.`tipo_id` ',
				'filterers' => array('empresa_id' => 'empresa_id'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			)
		),
		'tb_acompanhamento_colaborador' => array(   
			'acompanhamento_id' => array(
				'parent_table' => 'tb_acompanhamento',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`tb_acompanhamento`.`empresa_id`) || CHAR_LENGTH(if(`tb_acompanhamento`.`dta`,date_format(`tb_acompanhamento`.`dta`,\'%d/%m/%Y\'),\'\')), CONCAT_WS(\'\', IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`), CONCAT_WS(\'\',   `tb_empresa1`.`str_nome_fantasia`), \'\'), \' - \', if(`tb_acompanhamento`.`dta`,date_format(`tb_acompanhamento`.`dta`,\'%d/%m/%Y\'),\'\')), \'\')',
				'parent_from' => '`tb_acompanhamento` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_acompanhamento`.`empresa_id` LEFT JOIN `tb_contato` as tb_contato1 ON `tb_contato1`.`id`=`tb_acompanhamento`.`contato_id` LEFT JOIN `tb_contrato` as tb_contrato1 ON `tb_contrato1`.`id`=`tb_acompanhamento`.`contrato_id` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_acompanhamento`.`usuario_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'colaborador_id' => array(
				'parent_table' => 'tb_contratacao',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`tb_contratacao`.`str_candidato_nome`) || CHAR_LENGTH(`tb_contratacao`.`id`), CONCAT_WS(\'\', `tb_contratacao`.`str_candidato_nome`, \' - \', `tb_contratacao`.`id`), \'\')',
				'parent_from' => '`tb_contratacao` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'tb_indicador' => array(  
		),
		'tb_indicador_periodo' => array(   
			'indicador_id' => array(
				'parent_table' => 'tb_indicador',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`tb_indicador`.`str_departamento`) || CHAR_LENGTH(`tb_indicador`.`str_nome`), CONCAT_WS(\'\', `tb_indicador`.`str_departamento`, \' - \', `tb_indicador`.`str_nome`), \'\')',
				'parent_from' => '`tb_indicador` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			)
		),
		'tb_fatura' => array(   
			'empresa_id' => array(
				'parent_table' => 'tb_empresa',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_empresa`.`str_nome_fantasia`',
				'parent_from' => '`tb_empresa` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_empresa`.`str_responsavel` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_empresa`.`relacionamento_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			)
		),
		'tb_ajuste_colaborador' => array(   
			'colaborador_id' => array(
				'parent_table' => 'tb_contratacao',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`tb_contratacao`.`str_candidato_nome`) || CHAR_LENGTH(`tb_contratacao`.`id`), CONCAT_WS(\'\', `tb_contratacao`.`str_candidato_nome`, \'-\', `tb_contratacao`.`id`), \'\')',
				'parent_from' => '`tb_contratacao` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'gestor_id' => array(
				'parent_table' => 'tb_contratacao',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`tb_contratacao`.`str_candidato_nome`) || CHAR_LENGTH(`tb_contratacao`.`id`), CONCAT_WS(\'\', `tb_contratacao`.`str_candidato_nome`, \'-\', `tb_contratacao`.`id`), \'\')',
				'parent_from' => '`tb_contratacao` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `tb_contratacao`.`id`, IF(CHAR_LENGTH(`tb_contratacao`.`str_candidato_nome`) || CHAR_LENGTH(`tb_contratacao`.`id`), CONCAT_WS(\'\', `tb_contratacao`.`str_candidato_nome`, \'-\', `tb_contratacao`.`id`), \'\') FROM `tb_contratacao` WHERE `tb_contratacao`.`bol_gestor` = 1 ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			)
		),
		'tb_requerimento' => array(   
			'recrutador_id' => array(
				'parent_table' => 'tb_recrutador',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_recrutador`.`str_nome`',
				'parent_from' => '`tb_recrutador` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `tb_recrutador`.`id`, `tb_recrutador`.`str_nome` FROM `tb_recrutador` WHERE bol_recrutador = 1 AND bol_status = 1 ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'empresa_id' => array(
				'parent_table' => 'tb_empresa',
				'parent_pk_field' => 'id',
				'parent_caption' => '`tb_empresa`.`str_nome_fantasia`',
				'parent_from' => '`tb_empresa` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_empresa`.`str_responsavel` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_empresa`.`relacionamento_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'contato_id' => array(
				'parent_table' => 'tb_contato',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`tb_contato`.`str_primeiro_nome`) || CHAR_LENGTH(`tb_contato`.`str_sobrenome`), CONCAT_WS(\'\', `tb_contato`.`str_primeiro_nome`, \' \', `tb_contato`.`str_sobrenome`), \'\')',
				'parent_from' => '`tb_contato` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_contato`.`empresa_id` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_contato`.`tipo_id` ',
				'filterers' => array('empresa_id' => 'empresa_id'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			)
		)
	);

	// XSS prevention
	$xss = new CI_Input();
	$xss->charset = datalist_db_encoding;

	// receive and verify user input
	$table_name = $_REQUEST['t'];
	$field_name = $_REQUEST['f'];
	$search_id = makeSafe(from_utf8($_REQUEST['id']));
	$selected_text = from_utf8($_REQUEST['text']);
	$returnOptions = ($_REQUEST['o'] == 1 ? true : false);
	$page = intval($_REQUEST['p']);
	if($page < 1)  $page = 1;
	$skip = $results_per_page * ($page - 1);
	$search_term = makeSafe(from_utf8($_REQUEST['s']));

	if(!isset($lookups[$table_name][$field_name])) die('{ "error": "Invalid table or field." }');

	// can user access the requested table?
	$perm = getTablePermissions($table_name);
	if(!$perm[0] && !$search_id) die('{ "error": "' . addslashes($Translation['tableAccessDenied']) . '" }');

	$field = $lookups[$table_name][$field_name];

	$wheres = array();

	// search term provided?
	if($search_term){
		$wheres[] = "{$field['parent_caption']} like '%{$search_term}%'";
	}

	// any filterers specified?
	if(is_array($field['filterers'])){
		foreach($field['filterers'] as $filterer => $filterer_parent){
			$get = (isset($_REQUEST["filterer_{$filterer}"]) ? $_REQUEST["filterer_{$filterer}"] : false);
			if($get){
				$wheres[] = "`{$field['parent_table']}`.`$filterer_parent`='" . makeSafe($get) . "'";
			}
		}
	}

	// inherit permissions?
	if($field['inherit_permissions']){
		$inherit = permissions_sql($field['parent_table']);
		if($inherit === false && !$search_id) die($Translation['tableAccessDenied']);

		if($inherit['where']) $wheres[] = $inherit['where'];
		if($inherit['from']) $field['parent_from'] .= ", {$inherit['from']}";
	}

	// single value?
	if($field['list_type'] != 2 && $search_id){
		$wheres[] = "`{$field['parent_table']}`.`{$field['parent_pk_field']}`='{$search_id}'";
	}

	if(count($wheres)){
		$where = 'WHERE ' . implode(' AND ', $wheres);
	}

	// define the combo and return the code
	$combo = new DataCombo;
	if($field['custom_query']){
		$qm = array(); $custom_where = ''; $custom_order_by = '2';
		$combo->Query = $field['custom_query'];

		if(preg_match('/ order by (.*)$/i', $combo->Query, $qm)){
			$custom_order_by = $qm[1];
			$combo->Query = preg_replace('/ order by .*$/i', '', $combo->Query);
		}

		if(preg_match('/ where (.*)$/i', $combo->Query, $qm)){
			$custom_where = $qm[1];
			$combo->Query = preg_replace('/ where .*$/i', '', $combo->Query);
		}

		if($where && $custom_where){
			$combo->Query .=  " {$where} AND ({$custom_where}) ORDER BY {$custom_order_by}";
		}elseif($custom_where){
			$combo->Query .=  " WHERE {$custom_where} ORDER BY {$custom_order_by}";
		}else{
			$combo->Query .=  " {$where} ORDER BY {$custom_order_by}";
		}

		$query_match = array();
		preg_match('/select (.*) from (.*)$/i', $combo->Query, $query_match);

		if(isset($query_match[2])){
			$count_query = "SELECT count(1) FROM {$query_match[2]}";
		}else{
			$count_query = '';
		}
	}else{
		$combo->Query = "SELECT " . ($field['inherit_permissions'] ? 'DISTINCT ' : '') . "`{$field['parent_table']}`.`{$field['parent_pk_field']}`, {$field['parent_caption']} FROM {$field['parent_from']} {$where} ORDER BY 2";
		$count_query = "SELECT count(1) FROM {$field['parent_from']} {$where}";
	}
	$combo->table = $table_name;
	$combo->parent_table = $field['parent_table'];
	$combo->SelectName = $field_name;
	$combo->ListType = $field['list_type'];
	if($search_id){
		$combo->SelectedData = $search_id;
	}elseif($selected_text){
		$combo->SelectedData = getValueGivenCaption($combo->Query, $selected_text);
	}

	if($field['list_type'] == 2){
		$combo->Render();
		$combo->HTML = str_replace('<select ', '<select onchange="' . $field_name . '_changed();" ', $combo->HTML);

		// return response
		if($returnOptions){
			?><span id="<?php echo $field_name; ?>-combo-list"><?php echo $combo->HTML; ?></span><?php
		}else{
			?>
				<span id="<?php echo $field_name; ?>-match-text"><?php echo $combo->MatchText; ?></span>
				<input type="hidden" id="<?php echo $field_name; ?>" value="<?php echo html_attr($combo->SelectedData); ?>" />
			<?php
		}
	}else{
		/* return json */
		header('Content-type: application/json');

		if(!preg_match('/ limit .+/i', $combo->Query)){
			if(!$search_id) $combo->Query .= " LIMIT {$skip}, {$results_per_page}";
			if($search_id) $combo->Query .= " LIMIT 1";
		}

		$prepared_data = array();

		// specific caption provided and list_type is not radio?
		if(!$search_id && $selected_text){
			$search_id = getValueGivenCaption($combo->Query, $selected_text);
			if($search_id) $prepared_data[] = array('id' => to_utf8($search_id), 'text' => to_utf8($xss->xss_clean($selected_text)));
		}else{
			$res = sql($combo->Query, $eo);
			while($row = db_fetch_row($res)){
				if(empty($prepared_data) && $page == 1 && !$search_id && !$field['not_null']){
					$prepared_data[] = array('id' => empty_lookup_value, 'text' => to_utf8("<{$Translation['none']}>"));
				}

				$prepared_data[] = array('id' => to_utf8($row[0]), 'text' => to_utf8($xss->xss_clean($row[1])));
			}
		}

		if(empty($prepared_data)){ $prepared_data[] = array('id' => '', 'text' => to_utf8($Translation['No matches found!'])); }

		echo json_encode(array(
			'results' => $prepared_data,
			'more' => (@db_num_rows($res) >= $results_per_page),
			'elapsed' => round(microtime(true) - $start_ts, 3)
		));
	}

