<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	/* Configuration */
	/*************************************/

		$pcConfig = array(
			'tb_vaga' => array(   
				'empresa_id' => array(   
					'parent-table' => 'tb_empresa',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 2,
					'tab-label' => 'Vagas',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/chair.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(3 => 'Empresa', 4 => 'Aloca&#231;&#227;o', 5 => 'Recrutador', 6 => 'Posi&#231;&#227;o', 7 => 'Data de abertura', 8 => 'Qtd. de vagas em aberto', 9 => 'Prioridade', 10 => 'Status', 11 => 'Data fechamento', 12 => 'Data de previs&#227;o de fechamento', 13 => 'Observa&#231;&#245;es'),
					'display-field-names' => array(3 => 'empresa_id', 4 => 'str_alocacao', 5 => 'recrutador_id', 6 => 'str_posicao', 7 => 'dta_abertura', 8 => 'qtd_vagas', 9 => 'str_prioridade', 10 => 'str_status', 11 => 'dta_fechamento', 12 => 'dta_previsao_fechamento', 13 => 'str_obs'),
					'sortable-fields' => array(0 => '`tb_requerimento1`.`id`', 1 => '`tb_vaga`.`int_vaga_numero`', 2 => '`tb_vaga`.`id`', 3 => '`tb_empresa1`.`str_nome_fantasia`', 4 => '`tb_alocacao1`.`str_nome`', 5 => '`tb_recrutador1`.`str_nome`', 6 => 7, 7 => '`tb_vaga`.`dta_abertura`', 8 => '`tb_vaga`.`qtd_vagas`', 9 => 10, 10 => 11, 11 => '`tb_vaga`.`dta_fechamento`', 12 => '`tb_vaga`.`dta_previsao_fechamento`', 13 => 14, 14 => '`tb_vaga`.`dta_inicio`', 15 => 16),
					'records-per-page' => 10,
					'default-sort-by' => 7,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-tb_vaga',
					'template-printable' => 'children-tb_vaga-printable',
					'query' => "SELECT IF(    CHAR_LENGTH(`tb_requerimento1`.`id`), CONCAT_WS('',   `tb_requerimento1`.`id`), '') as 'requerimento_id', `tb_vaga`.`int_vaga_numero` as 'int_vaga_numero', `tb_vaga`.`id` as 'id', IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`), '') as 'empresa_id', IF(    CHAR_LENGTH(`tb_alocacao1`.`str_nome`), CONCAT_WS('',   `tb_alocacao1`.`str_nome`), '') as 'str_alocacao', IF(    CHAR_LENGTH(`tb_recrutador1`.`str_nome`), CONCAT_WS('',   `tb_recrutador1`.`str_nome`), '') as 'recrutador_id', `tb_vaga`.`str_posicao` as 'str_posicao', if(`tb_vaga`.`dta_abertura`,date_format(`tb_vaga`.`dta_abertura`,'%d/%m/%Y'),'') as 'dta_abertura', `tb_vaga`.`qtd_vagas` as 'qtd_vagas', `tb_vaga`.`str_prioridade` as 'str_prioridade', `tb_vaga`.`str_status` as 'str_status', if(`tb_vaga`.`dta_fechamento`,date_format(`tb_vaga`.`dta_fechamento`,'%d/%m/%Y'),'') as 'dta_fechamento', if(`tb_vaga`.`dta_previsao_fechamento`,date_format(`tb_vaga`.`dta_previsao_fechamento`,'%d/%m/%Y'),'') as 'dta_previsao_fechamento', `tb_vaga`.`str_obs` as 'str_obs', if(`tb_vaga`.`dta_inicio`,date_format(`tb_vaga`.`dta_inicio`,'%d/%m/%Y'),'') as 'dta_inicio', `tb_vaga`.`str_contratado_nome` as 'str_contratado_nome' FROM `tb_vaga` LEFT JOIN `tb_requerimento` as tb_requerimento1 ON `tb_requerimento1`.`id`=`tb_vaga`.`requerimento_id` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_vaga`.`empresa_id` LEFT JOIN `tb_alocacao` as tb_alocacao1 ON `tb_alocacao1`.`id`=`tb_vaga`.`str_alocacao` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_vaga`.`recrutador_id` "
				),
				'str_alocacao' => array(   
					'parent-table' => 'tb_alocacao',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 2,
					'tab-label' => 'Vagas',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/chair.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(3 => 'Empresa', 4 => 'Aloca&#231;&#227;o', 5 => 'Recrutador', 6 => 'Posi&#231;&#227;o', 7 => 'Data de abertura', 8 => 'Qtd. de vagas em aberto', 9 => 'Prioridade', 10 => 'Status', 11 => 'Data fechamento', 12 => 'Data de previs&#227;o de fechamento', 13 => 'Observa&#231;&#245;es'),
					'display-field-names' => array(3 => 'empresa_id', 4 => 'str_alocacao', 5 => 'recrutador_id', 6 => 'str_posicao', 7 => 'dta_abertura', 8 => 'qtd_vagas', 9 => 'str_prioridade', 10 => 'str_status', 11 => 'dta_fechamento', 12 => 'dta_previsao_fechamento', 13 => 'str_obs'),
					'sortable-fields' => array(0 => '`tb_requerimento1`.`id`', 1 => '`tb_vaga`.`int_vaga_numero`', 2 => '`tb_vaga`.`id`', 3 => '`tb_empresa1`.`str_nome_fantasia`', 4 => '`tb_alocacao1`.`str_nome`', 5 => '`tb_recrutador1`.`str_nome`', 6 => 7, 7 => '`tb_vaga`.`dta_abertura`', 8 => '`tb_vaga`.`qtd_vagas`', 9 => 10, 10 => 11, 11 => '`tb_vaga`.`dta_fechamento`', 12 => '`tb_vaga`.`dta_previsao_fechamento`', 13 => 14, 14 => '`tb_vaga`.`dta_inicio`', 15 => 16),
					'records-per-page' => 10,
					'default-sort-by' => 7,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-tb_vaga',
					'template-printable' => 'children-tb_vaga-printable',
					'query' => "SELECT IF(    CHAR_LENGTH(`tb_requerimento1`.`id`), CONCAT_WS('',   `tb_requerimento1`.`id`), '') as 'requerimento_id', `tb_vaga`.`int_vaga_numero` as 'int_vaga_numero', `tb_vaga`.`id` as 'id', IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`), '') as 'empresa_id', IF(    CHAR_LENGTH(`tb_alocacao1`.`str_nome`), CONCAT_WS('',   `tb_alocacao1`.`str_nome`), '') as 'str_alocacao', IF(    CHAR_LENGTH(`tb_recrutador1`.`str_nome`), CONCAT_WS('',   `tb_recrutador1`.`str_nome`), '') as 'recrutador_id', `tb_vaga`.`str_posicao` as 'str_posicao', if(`tb_vaga`.`dta_abertura`,date_format(`tb_vaga`.`dta_abertura`,'%d/%m/%Y'),'') as 'dta_abertura', `tb_vaga`.`qtd_vagas` as 'qtd_vagas', `tb_vaga`.`str_prioridade` as 'str_prioridade', `tb_vaga`.`str_status` as 'str_status', if(`tb_vaga`.`dta_fechamento`,date_format(`tb_vaga`.`dta_fechamento`,'%d/%m/%Y'),'') as 'dta_fechamento', if(`tb_vaga`.`dta_previsao_fechamento`,date_format(`tb_vaga`.`dta_previsao_fechamento`,'%d/%m/%Y'),'') as 'dta_previsao_fechamento', `tb_vaga`.`str_obs` as 'str_obs', if(`tb_vaga`.`dta_inicio`,date_format(`tb_vaga`.`dta_inicio`,'%d/%m/%Y'),'') as 'dta_inicio', `tb_vaga`.`str_contratado_nome` as 'str_contratado_nome' FROM `tb_vaga` LEFT JOIN `tb_requerimento` as tb_requerimento1 ON `tb_requerimento1`.`id`=`tb_vaga`.`requerimento_id` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_vaga`.`empresa_id` LEFT JOIN `tb_alocacao` as tb_alocacao1 ON `tb_alocacao1`.`id`=`tb_vaga`.`str_alocacao` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_vaga`.`recrutador_id` "
				)
			),
			'tb_entrevista' => array(   
				'empresa_id' => array(   
					'parent-table' => 'tb_empresa',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Atividades de RH',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/clock_red.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Empresa', 2 => 'Vaga', 3 => 'Recrutador', 4 => 'Data', 5 => 'Qtd. de contatos', 6 => 'Qtd. de entrevistas', 7 => 'Qtd. de encaminhamentos'),
					'display-field-names' => array(1 => 'empresa_id', 2 => 'vaga_id', 3 => 'recrutador_id', 4 => 'dta', 5 => 'int_qtd_contatos', 6 => 'int_qtd_entrevistas', 7 => 'int_qtd_encaminhamentos'),
					'sortable-fields' => array(0 => '`tb_entrevista`.`id`', 1 => '`tb_empresa1`.`str_nome_fantasia`', 2 => 3, 3 => '`tb_recrutador1`.`str_nome`', 4 => '`tb_entrevista`.`dta`', 5 => '`tb_entrevista`.`int_qtd_contatos`', 6 => '`tb_entrevista`.`int_qtd_entrevistas`', 7 => '`tb_entrevista`.`int_qtd_encaminhamentos`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-tb_entrevista',
					'template-printable' => 'children-tb_entrevista-printable',
					'query' => "SELECT `tb_entrevista`.`id` as 'id', IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`), '') as 'empresa_id', IF(    CHAR_LENGTH(`tb_vaga1`.`str_posicao`) || CHAR_LENGTH(`tb_alocacao1`.`str_nome`), CONCAT_WS('',   `tb_vaga1`.`str_posicao`, ' - ', `tb_alocacao1`.`str_nome`), '') as 'vaga_id', IF(    CHAR_LENGTH(`tb_recrutador1`.`str_nome`), CONCAT_WS('',   `tb_recrutador1`.`str_nome`), '') as 'recrutador_id', if(`tb_entrevista`.`dta`,date_format(`tb_entrevista`.`dta`,'%d/%m/%Y'),'') as 'dta', `tb_entrevista`.`int_qtd_contatos` as 'int_qtd_contatos', `tb_entrevista`.`int_qtd_entrevistas` as 'int_qtd_entrevistas', `tb_entrevista`.`int_qtd_encaminhamentos` as 'int_qtd_encaminhamentos' FROM `tb_entrevista` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_entrevista`.`empresa_id` LEFT JOIN `tb_vaga` as tb_vaga1 ON `tb_vaga1`.`id`=`tb_entrevista`.`vaga_id` LEFT JOIN `tb_alocacao` as tb_alocacao1 ON `tb_alocacao1`.`id`=`tb_vaga1`.`str_alocacao` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_entrevista`.`recrutador_id` "
				)
			),
			'tb_contratacao' => array(   
			),
			'tb_alocacao' => array(   
			),
			'tb_recrutador' => array(   
			),
			'tb_empresa' => array(   
			),
			'tb_prova_tipo' => array(   
			),
			'tb_contato' => array(   
				'empresa_id' => array(   
					'parent-table' => 'tb_empresa',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Contato',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/group.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Empresa', 2 => 'Primeiro nome', 3 => 'Sobrenome', 4 => 'N&#237;vel hier&#225;rquico', 5 => 'Relacionamento', 6 => 'E-mail 1', 8 => 'Telefone 1', 9 => 'Telefone 2', 11 => 'Cidade', 12 => 'UF'),
					'display-field-names' => array(1 => 'empresa_id', 2 => 'str_primeiro_nome', 3 => 'str_sobrenome', 4 => 'str_nivel', 5 => 'tipo_id', 6 => 'str_email1', 8 => 'str_telefone1', 9 => 'str_telefone2', 11 => 'cidade', 12 => 'uf'),
					'sortable-fields' => array(0 => '`tb_contato`.`id`', 1 => '`tb_empresa1`.`str_nome_fantasia`', 2 => 3, 3 => 4, 4 => 5, 5 => '`tb_contato_tipo1`.`str_nome`', 6 => 7, 7 => 8, 8 => 9, 9 => 10, 10 => 11, 11 => 12, 12 => 13, 13 => '`tb_contato`.`dta_cadastro`'),
					'records-per-page' => 10,
					'default-sort-by' => 0,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-tb_contato',
					'template-printable' => 'children-tb_contato-printable',
					'query' => "SELECT `tb_contato`.`id` as 'id', IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`), '') as 'empresa_id', `tb_contato`.`str_primeiro_nome` as 'str_primeiro_nome', `tb_contato`.`str_sobrenome` as 'str_sobrenome', `tb_contato`.`str_nivel` as 'str_nivel', IF(    CHAR_LENGTH(`tb_contato_tipo1`.`str_nome`), CONCAT_WS('',   `tb_contato_tipo1`.`str_nome`), '') as 'tipo_id', `tb_contato`.`str_email1` as 'str_email1', `tb_contato`.`str_email2` as 'str_email2', `tb_contato`.`str_telefone1` as 'str_telefone1', `tb_contato`.`str_telefone2` as 'str_telefone2', `tb_contato`.`str_telefone3` as 'str_telefone3', `tb_contato`.`cidade` as 'cidade', `tb_contato`.`uf` as 'uf', if(`tb_contato`.`dta_cadastro`,date_format(`tb_contato`.`dta_cadastro`,'%d/%m/%Y'),'') as 'dta_cadastro' FROM `tb_contato` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_contato`.`empresa_id` LEFT JOIN `tb_contato_tipo` as tb_contato_tipo1 ON `tb_contato_tipo1`.`id`=`tb_contato`.`tipo_id` "
				)
			),
			'tb_contato_tipo' => array(   
			),
			'tb_oportunidade' => array(   
				'empresa_id' => array(   
					'parent-table' => 'tb_empresa',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Oportunidades',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/ruby.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Tipo da demanda', 2 => 'Est&#225;gio', 3 => 'Empresa', 4 => 'Contato', 5 => 'Demanda', 6 => 'Data de in&#237;cio', 7 => 'Previs&#227;o para fechamento', 9 => 'Valor mensal', 10 => 'Quantidade de parcelas', 12 => 'Anexar proposta'),
					'display-field-names' => array(1 => 'tipo_id', 2 => 'estagio_id', 3 => 'empresa_id', 4 => 'contato_id', 5 => 'str_demanda', 6 => 'dta_inicio', 7 => 'dta_prev_fechamento', 9 => 'int_valor', 10 => 'int_parcelas', 12 => 'str_proposta'),
					'sortable-fields' => array(0 => '`tb_oportunidade`.`id`', 1 => '`tb_oportunidade_tipo1`.`str_nome`', 2 => '`tb_oportunidade_estagio1`.`str_nome`', 3 => '`tb_empresa1`.`str_nome_fantasia`', 4 => 5, 5 => 6, 6 => '`tb_oportunidade`.`dta_inicio`', 7 => '`tb_oportunidade`.`dta_prev_fechamento`', 8 => '`tb_oportunidade`.`int_probabilidade`', 9 => '`tb_oportunidade`.`int_valor`', 10 => '`tb_oportunidade`.`int_parcelas`', 11 => '`tb_oportunidade`.`dta_proposta`', 12 => 13, 13 => 14, 14 => 15),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-tb_oportunidade',
					'template-printable' => 'children-tb_oportunidade-printable',
					'query' => "SELECT `tb_oportunidade`.`id` as 'id', IF(    CHAR_LENGTH(`tb_oportunidade_tipo1`.`str_nome`), CONCAT_WS('',   `tb_oportunidade_tipo1`.`str_nome`), '') as 'tipo_id', IF(    CHAR_LENGTH(`tb_oportunidade_estagio1`.`str_nome`), CONCAT_WS('',   `tb_oportunidade_estagio1`.`str_nome`), '') as 'estagio_id', IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`), '') as 'empresa_id', IF(    CHAR_LENGTH(`tb_contato1`.`str_primeiro_nome`) || CHAR_LENGTH(`tb_empresa2`.`str_nome_fantasia`), CONCAT_WS('',   `tb_contato1`.`str_primeiro_nome`, ' - ', `tb_empresa2`.`str_nome_fantasia`), '') as 'contato_id', `tb_oportunidade`.`str_demanda` as 'str_demanda', if(`tb_oportunidade`.`dta_inicio`,date_format(`tb_oportunidade`.`dta_inicio`,'%d/%m/%Y'),'') as 'dta_inicio', if(`tb_oportunidade`.`dta_prev_fechamento`,date_format(`tb_oportunidade`.`dta_prev_fechamento`,'%d/%m/%Y'),'') as 'dta_prev_fechamento', `tb_oportunidade`.`int_probabilidade` as 'int_probabilidade', CONCAT('$', FORMAT(`tb_oportunidade`.`int_valor`, 2)) as 'int_valor', `tb_oportunidade`.`int_parcelas` as 'int_parcelas', if(`tb_oportunidade`.`dta_proposta`,date_format(`tb_oportunidade`.`dta_proposta`,'%d/%m/%Y'),'') as 'dta_proposta', `tb_oportunidade`.`str_proposta` as 'str_proposta', `tb_oportunidade`.`str_anotacoes` as 'str_anotacoes', `tb_oportunidade`.`str_responsavel` as 'str_responsavel' FROM `tb_oportunidade` LEFT JOIN `tb_oportunidade_tipo` as tb_oportunidade_tipo1 ON `tb_oportunidade_tipo1`.`id`=`tb_oportunidade`.`tipo_id` LEFT JOIN `tb_oportunidade_estagio` as tb_oportunidade_estagio1 ON `tb_oportunidade_estagio1`.`id`=`tb_oportunidade`.`estagio_id` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_oportunidade`.`empresa_id` LEFT JOIN `tb_contato` as tb_contato1 ON `tb_contato1`.`id`=`tb_oportunidade`.`contato_id` LEFT JOIN `tb_empresa` as tb_empresa2 ON `tb_empresa2`.`id`=`tb_contato1`.`empresa_id` "
				),
				'contato_id' => array(   
					'parent-table' => 'tb_contato',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Oportunidades',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/ruby.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Tipo da demanda', 2 => 'Est&#225;gio', 3 => 'Empresa', 4 => 'Contato', 5 => 'Demanda', 6 => 'Data de in&#237;cio', 7 => 'Previs&#227;o para fechamento', 9 => 'Valor mensal', 10 => 'Quantidade de parcelas', 12 => 'Anexar proposta'),
					'display-field-names' => array(1 => 'tipo_id', 2 => 'estagio_id', 3 => 'empresa_id', 4 => 'contato_id', 5 => 'str_demanda', 6 => 'dta_inicio', 7 => 'dta_prev_fechamento', 9 => 'int_valor', 10 => 'int_parcelas', 12 => 'str_proposta'),
					'sortable-fields' => array(0 => '`tb_oportunidade`.`id`', 1 => '`tb_oportunidade_tipo1`.`str_nome`', 2 => '`tb_oportunidade_estagio1`.`str_nome`', 3 => '`tb_empresa1`.`str_nome_fantasia`', 4 => 5, 5 => 6, 6 => '`tb_oportunidade`.`dta_inicio`', 7 => '`tb_oportunidade`.`dta_prev_fechamento`', 8 => '`tb_oportunidade`.`int_probabilidade`', 9 => '`tb_oportunidade`.`int_valor`', 10 => '`tb_oportunidade`.`int_parcelas`', 11 => '`tb_oportunidade`.`dta_proposta`', 12 => 13, 13 => 14, 14 => 15),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-tb_oportunidade',
					'template-printable' => 'children-tb_oportunidade-printable',
					'query' => "SELECT `tb_oportunidade`.`id` as 'id', IF(    CHAR_LENGTH(`tb_oportunidade_tipo1`.`str_nome`), CONCAT_WS('',   `tb_oportunidade_tipo1`.`str_nome`), '') as 'tipo_id', IF(    CHAR_LENGTH(`tb_oportunidade_estagio1`.`str_nome`), CONCAT_WS('',   `tb_oportunidade_estagio1`.`str_nome`), '') as 'estagio_id', IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`), '') as 'empresa_id', IF(    CHAR_LENGTH(`tb_contato1`.`str_primeiro_nome`) || CHAR_LENGTH(`tb_empresa2`.`str_nome_fantasia`), CONCAT_WS('',   `tb_contato1`.`str_primeiro_nome`, ' - ', `tb_empresa2`.`str_nome_fantasia`), '') as 'contato_id', `tb_oportunidade`.`str_demanda` as 'str_demanda', if(`tb_oportunidade`.`dta_inicio`,date_format(`tb_oportunidade`.`dta_inicio`,'%d/%m/%Y'),'') as 'dta_inicio', if(`tb_oportunidade`.`dta_prev_fechamento`,date_format(`tb_oportunidade`.`dta_prev_fechamento`,'%d/%m/%Y'),'') as 'dta_prev_fechamento', `tb_oportunidade`.`int_probabilidade` as 'int_probabilidade', CONCAT('$', FORMAT(`tb_oportunidade`.`int_valor`, 2)) as 'int_valor', `tb_oportunidade`.`int_parcelas` as 'int_parcelas', if(`tb_oportunidade`.`dta_proposta`,date_format(`tb_oportunidade`.`dta_proposta`,'%d/%m/%Y'),'') as 'dta_proposta', `tb_oportunidade`.`str_proposta` as 'str_proposta', `tb_oportunidade`.`str_anotacoes` as 'str_anotacoes', `tb_oportunidade`.`str_responsavel` as 'str_responsavel' FROM `tb_oportunidade` LEFT JOIN `tb_oportunidade_tipo` as tb_oportunidade_tipo1 ON `tb_oportunidade_tipo1`.`id`=`tb_oportunidade`.`tipo_id` LEFT JOIN `tb_oportunidade_estagio` as tb_oportunidade_estagio1 ON `tb_oportunidade_estagio1`.`id`=`tb_oportunidade`.`estagio_id` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_oportunidade`.`empresa_id` LEFT JOIN `tb_contato` as tb_contato1 ON `tb_contato1`.`id`=`tb_oportunidade`.`contato_id` LEFT JOIN `tb_empresa` as tb_empresa2 ON `tb_empresa2`.`id`=`tb_contato1`.`empresa_id` "
				)
			),
			'tb_atendimento' => array(   
				'empresa_id' => array(   
					'parent-table' => 'tb_empresa',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Atendimentos',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/comments.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Iniciativa', 2 => 'Empresa', 3 => 'Contato', 4 => 'Meio', 5 => 'Finalidade', 6 => 'Data', 7 => 'Campanha', 8 => 'Respons&#225;vel', 9 => 'Anota&#231;&#245;es'),
					'display-field-names' => array(1 => 'str_iniciativa', 2 => 'empresa_id', 3 => 'contato_id', 4 => 'str_meio', 5 => 'str_finalidade', 6 => 'dta', 7 => 'campanha_id', 8 => 'usuario_id', 9 => 'str_anotacoes'),
					'sortable-fields' => array(0 => '`tb_atendimento`.`id`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => 6, 6 => '`tb_atendimento`.`dta`', 7 => '`tb_campanha1`.`str_nome`', 8 => '`tb_recrutador1`.`str_nome`', 9 => 10),
					'records-per-page' => 10,
					'default-sort-by' => 6,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-tb_atendimento',
					'template-printable' => 'children-tb_atendimento-printable',
					'query' => "SELECT `tb_atendimento`.`id` as 'id', `tb_atendimento`.`str_iniciativa` as 'str_iniciativa', IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`) || CHAR_LENGTH(`tb_empresa1`.`id`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`, ' - ID ', `tb_empresa1`.`id`), '') as 'empresa_id', IF(    CHAR_LENGTH(`tb_contato1`.`str_primeiro_nome`) || CHAR_LENGTH(`tb_contato1`.`str_sobrenome`), CONCAT_WS('',   `tb_contato1`.`str_primeiro_nome`, ' ', `tb_contato1`.`str_sobrenome`), '') as 'contato_id', `tb_atendimento`.`str_meio` as 'str_meio', `tb_atendimento`.`str_finalidade` as 'str_finalidade', if(`tb_atendimento`.`dta`,date_format(`tb_atendimento`.`dta`,'%d/%m/%Y'),'') as 'dta', IF(    CHAR_LENGTH(`tb_campanha1`.`str_nome`), CONCAT_WS('',   `tb_campanha1`.`str_nome`), '') as 'campanha_id', IF(    CHAR_LENGTH(`tb_recrutador1`.`str_nome`), CONCAT_WS('',   `tb_recrutador1`.`str_nome`), '') as 'usuario_id', if(CHAR_LENGTH(`tb_atendimento`.`str_anotacoes`)>80, concat(left(`tb_atendimento`.`str_anotacoes`,80),' ...'), `tb_atendimento`.`str_anotacoes`) as 'str_anotacoes' FROM `tb_atendimento` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_atendimento`.`empresa_id` LEFT JOIN `tb_contato` as tb_contato1 ON `tb_contato1`.`id`=`tb_atendimento`.`contato_id` LEFT JOIN `tb_campanha` as tb_campanha1 ON `tb_campanha1`.`id`=`tb_atendimento`.`campanha_id` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_atendimento`.`usuario_id` "
				),
				'contato_id' => array(   
					'parent-table' => 'tb_contato',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Eventos',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/comments.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Iniciativa', 2 => 'Empresa', 3 => 'Contato', 4 => 'Meio', 5 => 'Finalidade', 6 => 'Data', 7 => 'Campanha', 8 => 'Respons&#225;vel', 9 => 'Anota&#231;&#245;es'),
					'display-field-names' => array(1 => 'str_iniciativa', 2 => 'empresa_id', 3 => 'contato_id', 4 => 'str_meio', 5 => 'str_finalidade', 6 => 'dta', 7 => 'campanha_id', 8 => 'usuario_id', 9 => 'str_anotacoes'),
					'sortable-fields' => array(0 => '`tb_atendimento`.`id`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => 6, 6 => '`tb_atendimento`.`dta`', 7 => '`tb_campanha1`.`str_nome`', 8 => '`tb_recrutador1`.`str_nome`', 9 => 10),
					'records-per-page' => 10,
					'default-sort-by' => 6,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-tb_atendimento',
					'template-printable' => 'children-tb_atendimento-printable',
					'query' => "SELECT `tb_atendimento`.`id` as 'id', `tb_atendimento`.`str_iniciativa` as 'str_iniciativa', IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`) || CHAR_LENGTH(`tb_empresa1`.`id`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`, ' - ID ', `tb_empresa1`.`id`), '') as 'empresa_id', IF(    CHAR_LENGTH(`tb_contato1`.`str_primeiro_nome`) || CHAR_LENGTH(`tb_contato1`.`str_sobrenome`), CONCAT_WS('',   `tb_contato1`.`str_primeiro_nome`, ' ', `tb_contato1`.`str_sobrenome`), '') as 'contato_id', `tb_atendimento`.`str_meio` as 'str_meio', `tb_atendimento`.`str_finalidade` as 'str_finalidade', if(`tb_atendimento`.`dta`,date_format(`tb_atendimento`.`dta`,'%d/%m/%Y'),'') as 'dta', IF(    CHAR_LENGTH(`tb_campanha1`.`str_nome`), CONCAT_WS('',   `tb_campanha1`.`str_nome`), '') as 'campanha_id', IF(    CHAR_LENGTH(`tb_recrutador1`.`str_nome`), CONCAT_WS('',   `tb_recrutador1`.`str_nome`), '') as 'usuario_id', if(CHAR_LENGTH(`tb_atendimento`.`str_anotacoes`)>80, concat(left(`tb_atendimento`.`str_anotacoes`,80),' ...'), `tb_atendimento`.`str_anotacoes`) as 'str_anotacoes' FROM `tb_atendimento` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_atendimento`.`empresa_id` LEFT JOIN `tb_contato` as tb_contato1 ON `tb_contato1`.`id`=`tb_atendimento`.`contato_id` LEFT JOIN `tb_campanha` as tb_campanha1 ON `tb_campanha1`.`id`=`tb_atendimento`.`campanha_id` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_atendimento`.`usuario_id` "
				)
			),
			'tb_oportunidade_tipo' => array(   
			),
			'tb_oportunidade_estagio' => array(   
			),
			'tb_acompanhamento' => array(   
				'empresa_id' => array(   
					'parent-table' => 'tb_empresa',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Acompanhamento de Contas',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/hot.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Conta', 2 => 'Contato', 3 => 'Contrato', 4 => 'Respons&#225;vel', 5 => 'Data', 6 => 'Meio de contato', 7 => 'Status geral', 8 => 'Clima do cliente', 9 => 'Clima da equipe'),
					'display-field-names' => array(1 => 'empresa_id', 2 => 'contato_id', 3 => 'contrato_id', 4 => 'usuario_id', 5 => 'dta', 6 => 'str_meio', 7 => 'str_statusgeral', 8 => 'str_clima_cliente', 9 => 'str_clima_equipe'),
					'sortable-fields' => array(0 => '`tb_acompanhamento`.`id`', 1 => '`tb_empresa1`.`str_nome_fantasia`', 2 => 3, 3 => '`tb_contrato1`.`str_nome`', 4 => '`tb_recrutador1`.`str_nome`', 5 => '`tb_acompanhamento`.`dta`', 6 => 7, 7 => 8, 8 => 9, 9 => 10, 10 => 11, 11 => 12),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-tb_acompanhamento',
					'template-printable' => 'children-tb_acompanhamento-printable',
					'query' => "SELECT `tb_acompanhamento`.`id` as 'id', IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`), '') as 'empresa_id', IF(    CHAR_LENGTH(`tb_contato1`.`str_primeiro_nome`) || CHAR_LENGTH(`tb_contato1`.`str_sobrenome`), CONCAT_WS('',   `tb_contato1`.`str_primeiro_nome`, ' ', `tb_contato1`.`str_sobrenome`), '') as 'contato_id', IF(    CHAR_LENGTH(`tb_contrato1`.`str_nome`), CONCAT_WS('',   `tb_contrato1`.`str_nome`), '') as 'contrato_id', IF(    CHAR_LENGTH(`tb_recrutador1`.`str_nome`), CONCAT_WS('',   `tb_recrutador1`.`str_nome`), '') as 'usuario_id', if(`tb_acompanhamento`.`dta`,date_format(`tb_acompanhamento`.`dta`,'%d/%m/%Y'),'') as 'dta', `tb_acompanhamento`.`str_meio` as 'str_meio', `tb_acompanhamento`.`str_statusgeral` as 'str_statusgeral', `tb_acompanhamento`.`str_clima_cliente` as 'str_clima_cliente', `tb_acompanhamento`.`str_clima_equipe` as 'str_clima_equipe', `tb_acompanhamento`.`str_observacoes` as 'str_observacoes', `tb_acompanhamento`.`str_acoes_corretivas` as 'str_acoes_corretivas' FROM `tb_acompanhamento` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_acompanhamento`.`empresa_id` LEFT JOIN `tb_contato` as tb_contato1 ON `tb_contato1`.`id`=`tb_acompanhamento`.`contato_id` LEFT JOIN `tb_contrato` as tb_contrato1 ON `tb_contrato1`.`id`=`tb_acompanhamento`.`contrato_id` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_acompanhamento`.`usuario_id` "
				),
				'contato_id' => array(   
					'parent-table' => 'tb_contato',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Acompanhamento de Contas',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/hot.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Conta', 2 => 'Contato', 3 => 'Contrato', 4 => 'Respons&#225;vel', 5 => 'Data', 6 => 'Meio de contato', 7 => 'Status geral', 8 => 'Clima do cliente', 9 => 'Clima da equipe'),
					'display-field-names' => array(1 => 'empresa_id', 2 => 'contato_id', 3 => 'contrato_id', 4 => 'usuario_id', 5 => 'dta', 6 => 'str_meio', 7 => 'str_statusgeral', 8 => 'str_clima_cliente', 9 => 'str_clima_equipe'),
					'sortable-fields' => array(0 => '`tb_acompanhamento`.`id`', 1 => '`tb_empresa1`.`str_nome_fantasia`', 2 => 3, 3 => '`tb_contrato1`.`str_nome`', 4 => '`tb_recrutador1`.`str_nome`', 5 => '`tb_acompanhamento`.`dta`', 6 => 7, 7 => 8, 8 => 9, 9 => 10, 10 => 11, 11 => 12),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-tb_acompanhamento',
					'template-printable' => 'children-tb_acompanhamento-printable',
					'query' => "SELECT `tb_acompanhamento`.`id` as 'id', IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`), '') as 'empresa_id', IF(    CHAR_LENGTH(`tb_contato1`.`str_primeiro_nome`) || CHAR_LENGTH(`tb_contato1`.`str_sobrenome`), CONCAT_WS('',   `tb_contato1`.`str_primeiro_nome`, ' ', `tb_contato1`.`str_sobrenome`), '') as 'contato_id', IF(    CHAR_LENGTH(`tb_contrato1`.`str_nome`), CONCAT_WS('',   `tb_contrato1`.`str_nome`), '') as 'contrato_id', IF(    CHAR_LENGTH(`tb_recrutador1`.`str_nome`), CONCAT_WS('',   `tb_recrutador1`.`str_nome`), '') as 'usuario_id', if(`tb_acompanhamento`.`dta`,date_format(`tb_acompanhamento`.`dta`,'%d/%m/%Y'),'') as 'dta', `tb_acompanhamento`.`str_meio` as 'str_meio', `tb_acompanhamento`.`str_statusgeral` as 'str_statusgeral', `tb_acompanhamento`.`str_clima_cliente` as 'str_clima_cliente', `tb_acompanhamento`.`str_clima_equipe` as 'str_clima_equipe', `tb_acompanhamento`.`str_observacoes` as 'str_observacoes', `tb_acompanhamento`.`str_acoes_corretivas` as 'str_acoes_corretivas' FROM `tb_acompanhamento` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_acompanhamento`.`empresa_id` LEFT JOIN `tb_contato` as tb_contato1 ON `tb_contato1`.`id`=`tb_acompanhamento`.`contato_id` LEFT JOIN `tb_contrato` as tb_contrato1 ON `tb_contrato1`.`id`=`tb_acompanhamento`.`contrato_id` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_acompanhamento`.`usuario_id` "
				)
			),
			'tb_contrato' => array(   
				'empresa_id' => array(   
					'parent-table' => 'tb_empresa',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Contratos',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/document_mark_as_final.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Conta', 2 => 'Nome', 3 => 'Data de in&#237;cio', 4 => 'Data de t&#233;rmino', 6 => 'Arquivo anexo', 7 => 'Ativo'),
					'display-field-names' => array(1 => 'empresa_id', 2 => 'str_nome', 3 => 'dta_inicio', 4 => 'dta_termino', 6 => 'str_anexo', 7 => 'bol_status'),
					'sortable-fields' => array(0 => '`tb_contrato`.`id`', 1 => '`tb_empresa1`.`str_nome_fantasia`', 2 => 3, 3 => '`tb_contrato`.`dta_inicio`', 4 => '`tb_contrato`.`dta_termino`', 5 => 6, 6 => 7, 7 => '`tb_contrato`.`bol_status`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-tb_contrato',
					'template-printable' => 'children-tb_contrato-printable',
					'query' => "SELECT `tb_contrato`.`id` as 'id', IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`), '') as 'empresa_id', `tb_contrato`.`str_nome` as 'str_nome', if(`tb_contrato`.`dta_inicio`,date_format(`tb_contrato`.`dta_inicio`,'%d/%m/%Y'),'') as 'dta_inicio', if(`tb_contrato`.`dta_termino`,date_format(`tb_contrato`.`dta_termino`,'%d/%m/%Y'),'') as 'dta_termino', `tb_contrato`.`str_detalhes` as 'str_detalhes', `tb_contrato`.`str_anexo` as 'str_anexo', concat('<i class=\"glyphicon glyphicon-', if(`tb_contrato`.`bol_status`, 'check', 'unchecked'), '\"></i>') as 'bol_status' FROM `tb_contrato` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_contrato`.`empresa_id` "
				)
			),
			'tb_campanha' => array(   
			),
			'tb_campanha_contato' => array(   
			),
			'tb_acompanhamento_colaborador' => array(   
				'acompanhamento_id' => array(   
					'parent-table' => 'tb_acompanhamento',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Acompanhamento individual',
					'auto-close' => true,
					'table-icon' => 'table.gif',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Data', 2 => 'Acompanhamento id', 3 => 'Colaborador id', 4 => 'Feedback', 6 => 'Respons&#225;vel'),
					'display-field-names' => array(1 => 'dta_data', 2 => 'acompanhamento_id', 3 => 'colaborador_id', 4 => 'str_tipo', 6 => 'str_responsavel'),
					'sortable-fields' => array(0 => '`tb_acompanhamento_colaborador`.`id`', 1 => '`tb_acompanhamento_colaborador`.`dta_data`', 2 => 3, 3 => 4, 4 => 5, 5 => 6, 6 => 7),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-tb_acompanhamento_colaborador',
					'template-printable' => 'children-tb_acompanhamento_colaborador-printable',
					'query' => "SELECT `tb_acompanhamento_colaborador`.`id` as 'id', if(`tb_acompanhamento_colaborador`.`dta_data`,date_format(`tb_acompanhamento_colaborador`.`dta_data`,'%d/%m/%Y'),'') as 'dta_data', IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`) || CHAR_LENGTH(if(`tb_acompanhamento1`.`dta`,date_format(`tb_acompanhamento1`.`dta`,'%d/%m/%Y'),'')), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`, ' - ', ' - ', if(`tb_acompanhamento1`.`dta`,date_format(`tb_acompanhamento1`.`dta`,'%d/%m/%Y'),'')), '') as 'acompanhamento_id', IF(    CHAR_LENGTH(`tb_contratacao1`.`str_candidato_nome`) || CHAR_LENGTH(`tb_contratacao1`.`id`), CONCAT_WS('',   `tb_contratacao1`.`str_candidato_nome`, ' - ', `tb_contratacao1`.`id`), '') as 'colaborador_id', `tb_acompanhamento_colaborador`.`str_tipo` as 'str_tipo', `tb_acompanhamento_colaborador`.`str_comentarios` as 'str_comentarios', `tb_acompanhamento_colaborador`.`str_responsavel` as 'str_responsavel' FROM `tb_acompanhamento_colaborador` LEFT JOIN `tb_acompanhamento` as tb_acompanhamento1 ON `tb_acompanhamento1`.`id`=`tb_acompanhamento_colaborador`.`acompanhamento_id` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_acompanhamento1`.`empresa_id` LEFT JOIN `tb_contratacao` as tb_contratacao1 ON `tb_contratacao1`.`id`=`tb_acompanhamento_colaborador`.`colaborador_id` "
				)
			),
			'tb_indicador' => array(   
			),
			'tb_indicador_periodo' => array(   
				'indicador_id' => array(   
					'parent-table' => 'tb_indicador',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Per&#237;odos dos indicadores',
					'auto-close' => true,
					'table-icon' => 'table.gif',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Indicador', 2 => 'Unidade', 3 => 'Vertical', 4 => 'Respons&#225;vel', 5 => 'Data', 6 => 'Sazonalidade', 7 => 'Meta', 8 => 'Meta ajustada', 9 => 'Realizado'),
					'display-field-names' => array(1 => 'indicador_id', 2 => 'str_unidade', 3 => 'str_vertical', 4 => 'str_responsavel', 5 => 'dta', 6 => 'flo_sazonalidade', 7 => 'int_meta', 8 => 'int_meta_ajustada', 9 => 'int_realizado'),
					'sortable-fields' => array(0 => '`tb_indicador_periodo`.`id`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => '`tb_indicador_periodo`.`dta`', 6 => '`tb_indicador_periodo`.`flo_sazonalidade`', 7 => '`tb_indicador_periodo`.`int_meta`', 8 => '`tb_indicador_periodo`.`int_meta_ajustada`', 9 => '`tb_indicador_periodo`.`int_realizado`'),
					'records-per-page' => 10,
					'default-sort-by' => 5,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-tb_indicador_periodo',
					'template-printable' => 'children-tb_indicador_periodo-printable',
					'query' => "SELECT `tb_indicador_periodo`.`id` as 'id', IF(    CHAR_LENGTH(`tb_indicador1`.`str_departamento`) || CHAR_LENGTH(`tb_indicador1`.`str_nome`), CONCAT_WS('',   `tb_indicador1`.`str_departamento`, ' - ', `tb_indicador1`.`str_nome`), '') as 'indicador_id', `tb_indicador_periodo`.`str_unidade` as 'str_unidade', `tb_indicador_periodo`.`str_vertical` as 'str_vertical', `tb_indicador_periodo`.`str_responsavel` as 'str_responsavel', if(`tb_indicador_periodo`.`dta`,date_format(`tb_indicador_periodo`.`dta`,'%d/%m/%Y'),'') as 'dta', `tb_indicador_periodo`.`flo_sazonalidade` as 'flo_sazonalidade', `tb_indicador_periodo`.`int_meta` as 'int_meta', `tb_indicador_periodo`.`int_meta_ajustada` as 'int_meta_ajustada', `tb_indicador_periodo`.`int_realizado` as 'int_realizado' FROM `tb_indicador_periodo` LEFT JOIN `tb_indicador` as tb_indicador1 ON `tb_indicador1`.`id`=`tb_indicador_periodo`.`indicador_id` "
				)
			),
			'tb_fatura' => array(   
				'empresa_id' => array(   
					'parent-table' => 'tb_empresa',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Faturamento',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/blogs.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Conta', 2 => 'Data de emiss&#227;o', 3 => 'Data de compet&#234;ncia', 4 => 'Valor total', 5 => 'N&#250;mero da nota', 6 => 'Observa&#231;&#245;es'),
					'display-field-names' => array(1 => 'empresa_id', 2 => 'dta_emissao', 3 => 'dta_competencia', 4 => 'flo_valor', 5 => 'int_nf', 6 => 'str_observacoes'),
					'sortable-fields' => array(0 => '`tb_fatura`.`id`', 1 => '`tb_empresa1`.`str_nome_fantasia`', 2 => '`tb_fatura`.`dta_emissao`', 3 => '`tb_fatura`.`dta_competencia`', 4 => '`tb_fatura`.`flo_valor`', 5 => '`tb_fatura`.`int_nf`', 6 => 7),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-tb_fatura',
					'template-printable' => 'children-tb_fatura-printable',
					'query' => "SELECT `tb_fatura`.`id` as 'id', IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`), '') as 'empresa_id', if(`tb_fatura`.`dta_emissao`,date_format(`tb_fatura`.`dta_emissao`,'%d/%m/%Y'),'') as 'dta_emissao', if(`tb_fatura`.`dta_competencia`,date_format(`tb_fatura`.`dta_competencia`,'%d/%m/%Y'),'') as 'dta_competencia', `tb_fatura`.`flo_valor` as 'flo_valor', `tb_fatura`.`int_nf` as 'int_nf', `tb_fatura`.`str_observacoes` as 'str_observacoes' FROM `tb_fatura` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_fatura`.`empresa_id` "
				)
			),
			'tb_ajuste_colaborador' => array(   
			),
			'tb_requerimento' => array(   
			)
		);

	/*************************************/
	/* End of configuration */


	$currDir = dirname(__FILE__);
	include("{$currDir}/defaultLang.php");
	include("{$currDir}/language.php");
	include("{$currDir}/lib.php");
	@header('Content-Type: text/html; charset=' . datalist_db_encoding);

	handle_maintenance();

	/**
	* dynamic configuration based on current user's permissions
	* $userPCConfig array is populated only with parent tables where the user has access to
	* at least one child table
	*/
	$userPCConfig = array();
	foreach($pcConfig as $pcChildTable => $ChildrenLookups){
		$permChild = getTablePermissions($pcChildTable);
		if($permChild[2]){ // user can view records of the child table, so proceed to check children lookups
			foreach($ChildrenLookups as $ChildLookupField => $ChildConfig){
				$permParent = getTablePermissions($ChildConfig['parent-table']);
				if($permParent[2]){ // user can view records of parent table
					$userPCConfig[$pcChildTable][$ChildLookupField] = $pcConfig[$pcChildTable][$ChildLookupField];
					// show add new only if configured above AND the user has insert permission
					if($permChild[1] && $pcConfig[$pcChildTable][$ChildLookupField]['display-add-new']){
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = true;
					}else{
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = false;
					}
				}
			}
		}
	}

	/* Receive, UTF-convert, and validate parameters */
	$ParentTable = $_REQUEST['ParentTable']; // needed only with operation=show-children, will be validated in the processing code
	$ChildTable = $_REQUEST['ChildTable'];
		if(!in_array($ChildTable, array_keys($userPCConfig))){
			/* defaults to first child table in config array if not provided */
			$ChildTable = current(array_keys($userPCConfig));
		}
		if(!$ChildTable){ die('<!-- No tables accessible to current user -->'); }
	$SelectedID = strip_tags($_REQUEST['SelectedID']);
	$ChildLookupField = $_REQUEST['ChildLookupField'];
		if(!in_array($ChildLookupField, array_keys($userPCConfig[$ChildTable]))){
			/* defaults to first lookup in current child config array if not provided */
			$ChildLookupField = current(array_keys($userPCConfig[$ChildTable]));
		}
	$Page = intval($_REQUEST['Page']);
		if($Page < 1){
			$Page = 1;
		}
	$SortBy = ($_REQUEST['SortBy'] != '' ? abs(intval($_REQUEST['SortBy'])) : false);
		if(!in_array($SortBy, array_keys($userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields']), true)){
			$SortBy = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-by'];
		}
	$SortDirection = strtolower($_REQUEST['SortDirection']);
		if(!in_array($SortDirection, array('asc', 'desc'))){
			$SortDirection = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-direction'];
		}
	$Operation = strtolower($_REQUEST['Operation']);
		if(!in_array($Operation, array('get-records', 'show-children', 'get-records-printable', 'show-children-printable'))){
			$Operation = 'get-records';
		}

	/* process requested operation */
	switch($Operation){
		/************************************************/
		case 'show-children':
			/* populate HTML and JS content with children tabs */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups){
				foreach($childLookups as $ChildLookupField => $childConfig){
					if($childConfig['parent-table'] == $ParentTable){
						$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\" />" : '');
						$tabLabels .= sprintf('<li%s><a href="#panel_%s-%s" id="tab_%s-%s" data-toggle="tab">%s%s</a></li>' . "\n\t\t\t\t\t",($tabLabels ? '' : ' class="active"'), $ChildTable, $ChildLookupField, $ChildTable, $ChildLookupField, $TableIcon, $childConfig['tab-label']);
						$tabPanels .= sprintf('<div id="panel_%s-%s" class="tab-pane%s"><img src="loading.gif" align="top" />%s</div>' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, ($tabPanels ? '' : ' active'), $Translation['Loading ...']);
						$tabLoaders .= sprintf('post("parent-children.php", { ChildTable: "%s", ChildLookupField: "%s", SelectedID: "%s", Page: 1, SortBy: "", SortDirection: "", Operation: "get-records" }, "panel_%s-%s");' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, addslashes($SelectedID), $ChildTable, $ChildLookupField);
					}
				}
			}

			if(!$tabLabels){ die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs">
				<ul class="nav nav-tabs">
					<?php echo $tabLabels; ?>
				</ul>
				<span id="pc-loading"></span>
			</div>
			<div class="tab-content"><?php echo $tabPanels; ?></div>

			<script>
				$j(function(){
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded){
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'show-children-printable':
			/* populate HTML and JS content with children buttons */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups){
				foreach($childLookups as $ChildLookupField => $childConfig){
					if($childConfig['parent-table'] == $ParentTable){
						$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\" />" : '');
						$tabLabels .= sprintf('<button type="button" class="btn btn-default" data-target="#panel_%s-%s" id="tab_%s-%s" data-toggle="collapse">%s %s</button>' . "\n\t\t\t\t\t", $ChildTable, $ChildLookupField, $ChildTable, $ChildLookupField, $TableIcon, $childConfig['tab-label']);
						$tabPanels .= sprintf('<div id="panel_%s-%s" class="collapse"><img src="loading.gif" align="top" />%s</div>' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, $Translation['Loading ...']);
						$tabLoaders .= sprintf('post("parent-children.php", { ChildTable: "%s", ChildLookupField: "%s", SelectedID: "%s", Page: 1, SortBy: "", SortDirection: "", Operation: "get-records-printable" }, "panel_%s-%s");' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, addslashes($SelectedID), $ChildTable, $ChildLookupField);
					}
				}
			}

			if(!$tabLabels){ die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs" class="hidden-print">
				<div class="btn-group btn-group-lg">
					<?php echo $tabLabels; ?>
				</div>
				<span id="pc-loading"></span>
			</div>
			<div class="vspacer-lg"><?php echo $tabPanels; ?></div>

			<script>
				$j(function(){
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded){
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'get-records-printable':
		default: /* default is 'get-records' */

			if($Operation == 'get-records-printable'){
				$userPCConfig[$ChildTable][$ChildLookupField]['records-per-page'] = 2000;
			}

			// build the user permissions limiter
			$permissionsWhere = $permissionsJoin = '';
			$permChild = getTablePermissions($ChildTable);
			if($permChild[2] == 1){ // user can view only his own records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND LCASE(`membership_userrecords`.`memberID`)='".getLoggedMemberID()."'";
			}elseif($permChild[2] == 2){ // user can view only his group's records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND `membership_userrecords`.`groupID`='".getLoggedGroupID()."'";
			}elseif($permChild[2] == 3){ // user can view all records
				/* that's the only case remaining ... no need to modify the query in this case */
			}
			$permissionsJoin = ($permissionsWhere ? ", `membership_userrecords`" : '');

			// build the count query
			$forcedWhere = $userPCConfig[$ChildTable][$ChildLookupField]['forced-where'];
			$query = 
				preg_replace('/^select .* from /i', 'SELECT count(1) FROM ', $userPCConfig[$ChildTable][$ChildLookupField]['query']) .
				$permissionsJoin . " WHERE " .
				($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
				($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
				"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'";
			$totalMatches = sqlValue($query);

			// make sure $Page is <= max pages
			$maxPage = ceil($totalMatches / $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']);
			if($Page > $maxPage){ $Page = $maxPage; }

			// initiate output data array
			$data = array(
				'config' => $userPCConfig[$ChildTable][$ChildLookupField],
				'parameters' => array(
					'ChildTable' => $ChildTable,
					'ChildLookupField' => $ChildLookupField,
					'SelectedID' => $SelectedID,
					'Page' => $Page,
					'SortBy' => $SortBy,
					'SortDirection' => $SortDirection,
					'Operation' => $Operation
				),
				'records' => array(),
				'totalMatches' => $totalMatches
			);

			// build the data query
			if($totalMatches){ // if we have at least one record, proceed with fetching data
				$startRecord = $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page'] * ($Page - 1);
				$data['query'] = 
					$userPCConfig[$ChildTable][$ChildLookupField]['query'] .
					$permissionsJoin . " WHERE " .
					($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
					($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
					"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'" . 
					($SortBy !== false && $userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields'][$SortBy] ? " ORDER BY {$userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields'][$SortBy]} $SortDirection" : '') .
					" LIMIT $startRecord, {$userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']}";
				$res = sql($data['query'], $eo);
				while($row = db_fetch_row($res)){
					$data['records'][$row[$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key-index']]] = $row;
				}
			}else{ // if no matching records
				$startRecord = 0;
			}

			if($Operation == 'get-records-printable'){
				$response = loadView($userPCConfig[$ChildTable][$ChildLookupField]['template-printable'], $data);
			}else{
				$response = loadView($userPCConfig[$ChildTable][$ChildLookupField]['template'], $data);
			}

			// change name space to ensure uniqueness
			$uniqueNameSpace = $ChildTable.ucfirst($ChildLookupField).'GetRecords';
			echo str_replace("{$ChildTable}GetChildrenRecordsList", $uniqueNameSpace, $response);
		/************************************************/
	}
