<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/tb_atendimento.php");
	include("$currDir/tb_atendimento_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('tb_atendimento');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "tb_atendimento";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`tb_atendimento`.`id`" => "id",
		"`tb_atendimento`.`str_iniciativa`" => "str_iniciativa",
		"IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`) || CHAR_LENGTH(`tb_empresa1`.`id`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`, ' - ID ', `tb_empresa1`.`id`), '') /* Empresa */" => "empresa_id",
		"IF(    CHAR_LENGTH(`tb_contato1`.`str_primeiro_nome`) || CHAR_LENGTH(`tb_contato1`.`str_sobrenome`), CONCAT_WS('',   `tb_contato1`.`str_primeiro_nome`, ' ', `tb_contato1`.`str_sobrenome`), '') /* Contato */" => "contato_id",
		"`tb_atendimento`.`str_meio`" => "str_meio",
		"`tb_atendimento`.`str_finalidade`" => "str_finalidade",
		"if(`tb_atendimento`.`dta`,date_format(`tb_atendimento`.`dta`,'%d/%m/%Y'),'')" => "dta",
		"IF(    CHAR_LENGTH(`tb_campanha1`.`str_nome`), CONCAT_WS('',   `tb_campanha1`.`str_nome`), '') /* Campanha */" => "campanha_id",
		"IF(    CHAR_LENGTH(`tb_recrutador1`.`str_nome`), CONCAT_WS('',   `tb_recrutador1`.`str_nome`), '') /* Respons&#225;vel */" => "usuario_id",
		"if(CHAR_LENGTH(`tb_atendimento`.`str_anotacoes`)>80, concat(left(`tb_atendimento`.`str_anotacoes`,80),' ...'), `tb_atendimento`.`str_anotacoes`)" => "str_anotacoes"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`tb_atendimento`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`tb_atendimento`.`dta`',
		8 => '`tb_campanha1`.`str_nome`',
		9 => '`tb_recrutador1`.`str_nome`',
		10 => 10
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`tb_atendimento`.`id`" => "id",
		"`tb_atendimento`.`str_iniciativa`" => "str_iniciativa",
		"IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`) || CHAR_LENGTH(`tb_empresa1`.`id`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`, ' - ID ', `tb_empresa1`.`id`), '') /* Empresa */" => "empresa_id",
		"IF(    CHAR_LENGTH(`tb_contato1`.`str_primeiro_nome`) || CHAR_LENGTH(`tb_contato1`.`str_sobrenome`), CONCAT_WS('',   `tb_contato1`.`str_primeiro_nome`, ' ', `tb_contato1`.`str_sobrenome`), '') /* Contato */" => "contato_id",
		"`tb_atendimento`.`str_meio`" => "str_meio",
		"`tb_atendimento`.`str_finalidade`" => "str_finalidade",
		"if(`tb_atendimento`.`dta`,date_format(`tb_atendimento`.`dta`,'%d/%m/%Y'),'')" => "dta",
		"IF(    CHAR_LENGTH(`tb_campanha1`.`str_nome`), CONCAT_WS('',   `tb_campanha1`.`str_nome`), '') /* Campanha */" => "campanha_id",
		"IF(    CHAR_LENGTH(`tb_recrutador1`.`str_nome`), CONCAT_WS('',   `tb_recrutador1`.`str_nome`), '') /* Respons&#225;vel */" => "usuario_id",
		"`tb_atendimento`.`str_anotacoes`" => "str_anotacoes"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`tb_atendimento`.`id`" => "ID",
		"`tb_atendimento`.`str_iniciativa`" => "Iniciativa",
		"IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`) || CHAR_LENGTH(`tb_empresa1`.`id`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`, ' - ID ', `tb_empresa1`.`id`), '') /* Empresa */" => "Empresa",
		"IF(    CHAR_LENGTH(`tb_contato1`.`str_primeiro_nome`) || CHAR_LENGTH(`tb_contato1`.`str_sobrenome`), CONCAT_WS('',   `tb_contato1`.`str_primeiro_nome`, ' ', `tb_contato1`.`str_sobrenome`), '') /* Contato */" => "Contato",
		"`tb_atendimento`.`str_meio`" => "Meio",
		"`tb_atendimento`.`str_finalidade`" => "Finalidade",
		"`tb_atendimento`.`dta`" => "Data",
		"IF(    CHAR_LENGTH(`tb_campanha1`.`str_nome`), CONCAT_WS('',   `tb_campanha1`.`str_nome`), '') /* Campanha */" => "Campanha",
		"IF(    CHAR_LENGTH(`tb_recrutador1`.`str_nome`), CONCAT_WS('',   `tb_recrutador1`.`str_nome`), '') /* Respons&#225;vel */" => "Respons&#225;vel",
		"`tb_atendimento`.`str_anotacoes`" => "Anota&#231;&#245;es"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`tb_atendimento`.`id`" => "id",
		"`tb_atendimento`.`str_iniciativa`" => "str_iniciativa",
		"IF(    CHAR_LENGTH(`tb_empresa1`.`str_nome_fantasia`) || CHAR_LENGTH(`tb_empresa1`.`id`), CONCAT_WS('',   `tb_empresa1`.`str_nome_fantasia`, ' - ID ', `tb_empresa1`.`id`), '') /* Empresa */" => "empresa_id",
		"IF(    CHAR_LENGTH(`tb_contato1`.`str_primeiro_nome`) || CHAR_LENGTH(`tb_contato1`.`str_sobrenome`), CONCAT_WS('',   `tb_contato1`.`str_primeiro_nome`, ' ', `tb_contato1`.`str_sobrenome`), '') /* Contato */" => "contato_id",
		"`tb_atendimento`.`str_meio`" => "str_meio",
		"`tb_atendimento`.`str_finalidade`" => "str_finalidade",
		"if(`tb_atendimento`.`dta`,date_format(`tb_atendimento`.`dta`,'%d/%m/%Y'),'')" => "dta",
		"IF(    CHAR_LENGTH(`tb_campanha1`.`str_nome`), CONCAT_WS('',   `tb_campanha1`.`str_nome`), '') /* Campanha */" => "campanha_id",
		"IF(    CHAR_LENGTH(`tb_recrutador1`.`str_nome`), CONCAT_WS('',   `tb_recrutador1`.`str_nome`), '') /* Respons&#225;vel */" => "usuario_id",
		"`tb_atendimento`.`str_anotacoes`" => "Anota&#231;&#245;es"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'empresa_id' => 'Empresa', 'contato_id' => 'Contato', 'campanha_id' => 'Campanha', 'usuario_id' => 'Respons&#225;vel');

	$x->QueryFrom = "`tb_atendimento` LEFT JOIN `tb_empresa` as tb_empresa1 ON `tb_empresa1`.`id`=`tb_atendimento`.`empresa_id` LEFT JOIN `tb_contato` as tb_contato1 ON `tb_contato1`.`id`=`tb_atendimento`.`contato_id` LEFT JOIN `tb_campanha` as tb_campanha1 ON `tb_campanha1`.`id`=`tb_atendimento`.`campanha_id` LEFT JOIN `tb_recrutador` as tb_recrutador1 ON `tb_recrutador1`.`id`=`tb_atendimento`.`usuario_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 30;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "tb_atendimento_view.php";
	$x->RedirectAfterInsert = "tb_atendimento_view.php";
	$x->TableTitle = "Atendimentos";
	$x->TableIcon = "resources/table_icons/comments.png";
	$x->PrimaryKey = "`tb_atendimento`.`id`";
	$x->DefaultSortField = '`tb_atendimento`.`dta`';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Iniciativa", "Empresa", "Contato", "Meio", "Finalidade", "Data", "Campanha", "Respons&#225;vel", "Anota&#231;&#245;es");
	$x->ColFieldName = array('str_iniciativa', 'empresa_id', 'contato_id', 'str_meio', 'str_finalidade', 'dta', 'campanha_id', 'usuario_id', 'str_anotacoes');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10);

	// template paths below are based on the app main directory
	$x->Template = 'templates/tb_atendimento_templateTV.html';
	$x->SelectedTemplate = 'templates/tb_atendimento_templateTVS.html';
	$x->TemplateDV = 'templates/tb_atendimento_templateDV.html';
	$x->TemplateDVP = 'templates/tb_atendimento_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tb_atendimento`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='tb_atendimento' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tb_atendimento`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='tb_atendimento' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`tb_atendimento`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: tb_atendimento_init
	$render=TRUE;
	if(function_exists('tb_atendimento_init')){
		$args=array();
		$render=tb_atendimento_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tb_atendimento_header
	$headerCode='';
	if(function_exists('tb_atendimento_header')){
		$args=array();
		$headerCode=tb_atendimento_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: tb_atendimento_footer
	$footerCode='';
	if(function_exists('tb_atendimento_footer')){
		$args=array();
		$footerCode=tb_atendimento_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>