<?php

// Data functions (insert, update, delete, form) for table tb_contato

// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

function tb_contato_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('tb_contato');
	if(!$arrPerm[1]){
		return false;
	}

	$data['empresa_id'] = makeSafe($_REQUEST['empresa_id']);
		if($data['empresa_id'] == empty_lookup_value){ $data['empresa_id'] = ''; }
	$data['str_primeiro_nome'] = makeSafe($_REQUEST['str_primeiro_nome']);
		if($data['str_primeiro_nome'] == empty_lookup_value){ $data['str_primeiro_nome'] = ''; }
	$data['str_sobrenome'] = makeSafe($_REQUEST['str_sobrenome']);
		if($data['str_sobrenome'] == empty_lookup_value){ $data['str_sobrenome'] = ''; }
	$data['str_nivel'] = makeSafe($_REQUEST['str_nivel']);
		if($data['str_nivel'] == empty_lookup_value){ $data['str_nivel'] = ''; }
	$data['tipo_id'] = makeSafe($_REQUEST['tipo_id']);
		if($data['tipo_id'] == empty_lookup_value){ $data['tipo_id'] = ''; }
	$data['str_email1'] = makeSafe($_REQUEST['str_email1']);
		if($data['str_email1'] == empty_lookup_value){ $data['str_email1'] = ''; }
	$data['str_email2'] = makeSafe($_REQUEST['str_email2']);
		if($data['str_email2'] == empty_lookup_value){ $data['str_email2'] = ''; }
	$data['str_telefone1'] = makeSafe($_REQUEST['str_telefone1']);
		if($data['str_telefone1'] == empty_lookup_value){ $data['str_telefone1'] = ''; }
	$data['str_telefone2'] = makeSafe($_REQUEST['str_telefone2']);
		if($data['str_telefone2'] == empty_lookup_value){ $data['str_telefone2'] = ''; }
	$data['str_telefone3'] = makeSafe($_REQUEST['str_telefone3']);
		if($data['str_telefone3'] == empty_lookup_value){ $data['str_telefone3'] = ''; }
	$data['cidade'] = makeSafe($_REQUEST['cidade']);
		if($data['cidade'] == empty_lookup_value){ $data['cidade'] = ''; }
	$data['uf'] = makeSafe($_REQUEST['uf']);
		if($data['uf'] == empty_lookup_value){ $data['uf'] = ''; }
	$data['dta_cadastro'] = parseCode('<%%creationDate%%>', true, true);
	if($data['empresa_id']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Empresa': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['str_primeiro_nome']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Primeiro nome': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['str_nivel']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'N&#237;vel hier&#225;rquico': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['tipo_id']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Relacionamento': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['str_email1']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'E-mail 1': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: tb_contato_before_insert
	if(function_exists('tb_contato_before_insert')){
		$args=array();
		if(!tb_contato_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `tb_contato` set       `empresa_id`=' . (($data['empresa_id'] !== '' && $data['empresa_id'] !== NULL) ? "'{$data['empresa_id']}'" : 'NULL') . ', `str_primeiro_nome`=' . (($data['str_primeiro_nome'] !== '' && $data['str_primeiro_nome'] !== NULL) ? "'{$data['str_primeiro_nome']}'" : 'NULL') . ', `str_sobrenome`=' . (($data['str_sobrenome'] !== '' && $data['str_sobrenome'] !== NULL) ? "'{$data['str_sobrenome']}'" : 'NULL') . ', `str_nivel`=' . (($data['str_nivel'] !== '' && $data['str_nivel'] !== NULL) ? "'{$data['str_nivel']}'" : 'NULL') . ', `tipo_id`=' . (($data['tipo_id'] !== '' && $data['tipo_id'] !== NULL) ? "'{$data['tipo_id']}'" : 'NULL') . ', `str_email1`=' . (($data['str_email1'] !== '' && $data['str_email1'] !== NULL) ? "'{$data['str_email1']}'" : 'NULL') . ', `str_email2`=' . (($data['str_email2'] !== '' && $data['str_email2'] !== NULL) ? "'{$data['str_email2']}'" : 'NULL') . ', `str_telefone1`=' . (($data['str_telefone1'] !== '' && $data['str_telefone1'] !== NULL) ? "'{$data['str_telefone1']}'" : 'NULL') . ', `str_telefone2`=' . (($data['str_telefone2'] !== '' && $data['str_telefone2'] !== NULL) ? "'{$data['str_telefone2']}'" : 'NULL') . ', `str_telefone3`=' . (($data['str_telefone3'] !== '' && $data['str_telefone3'] !== NULL) ? "'{$data['str_telefone3']}'" : 'NULL') . ', `cidade`=' . (($data['cidade'] !== '' && $data['cidade'] !== NULL) ? "'{$data['cidade']}'" : 'NULL') . ', `uf`=' . (($data['uf'] !== '' && $data['uf'] !== NULL) ? "'{$data['uf']}'" : 'NULL') . ', `dta_cadastro`=' . "'{$data['dta_cadastro']}'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"tb_contato_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: tb_contato_after_insert
	if(function_exists('tb_contato_after_insert')){
		$res = sql("select * from `tb_contato` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!tb_contato_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('tb_contato', $recID, getLoggedMemberID());

	return $recID;
}

function tb_contato_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('tb_contato');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tb_contato' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tb_contato' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: tb_contato_before_delete
	if(function_exists('tb_contato_before_delete')){
		$args=array();
		if(!tb_contato_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: tb_oportunidade
	$res = sql("select `id` from `tb_contato` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `tb_oportunidade` where `contato_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_oportunidade", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_oportunidade", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tb_contato_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tb_contato_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: tb_atendimento
	$res = sql("select `id` from `tb_contato` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `tb_atendimento` where `contato_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_atendimento", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_atendimento", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tb_contato_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tb_contato_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: tb_acompanhamento
	$res = sql("select `id` from `tb_contato` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `tb_acompanhamento` where `contato_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_acompanhamento", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_acompanhamento", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tb_contato_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tb_contato_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: tb_campanha_contato
	$res = sql("select `id` from `tb_contato` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `tb_campanha_contato` where `contato_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_campanha_contato", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_campanha_contato", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tb_contato_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tb_contato_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: tb_requerimento
	$res = sql("select `id` from `tb_contato` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `tb_requerimento` where `contato_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_requerimento", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_requerimento", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tb_contato_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tb_contato_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `tb_contato` where `id`='$selected_id'", $eo);

	// hook: tb_contato_after_delete
	if(function_exists('tb_contato_after_delete')){
		$args=array();
		tb_contato_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='tb_contato' and pkValue='$selected_id'", $eo);
}

function tb_contato_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('tb_contato');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tb_contato' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tb_contato' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['empresa_id'] = makeSafe($_REQUEST['empresa_id']);
		if($data['empresa_id'] == empty_lookup_value){ $data['empresa_id'] = ''; }
	if($data['empresa_id']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Empresa': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['str_primeiro_nome'] = makeSafe($_REQUEST['str_primeiro_nome']);
		if($data['str_primeiro_nome'] == empty_lookup_value){ $data['str_primeiro_nome'] = ''; }
	if($data['str_primeiro_nome']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Primeiro nome': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['str_sobrenome'] = makeSafe($_REQUEST['str_sobrenome']);
		if($data['str_sobrenome'] == empty_lookup_value){ $data['str_sobrenome'] = ''; }
	$data['str_nivel'] = makeSafe($_REQUEST['str_nivel']);
		if($data['str_nivel'] == empty_lookup_value){ $data['str_nivel'] = ''; }
	if($data['str_nivel']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'N&#237;vel hier&#225;rquico': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['tipo_id'] = makeSafe($_REQUEST['tipo_id']);
		if($data['tipo_id'] == empty_lookup_value){ $data['tipo_id'] = ''; }
	if($data['tipo_id']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Relacionamento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['str_email1'] = makeSafe($_REQUEST['str_email1']);
		if($data['str_email1'] == empty_lookup_value){ $data['str_email1'] = ''; }
	if($data['str_email1']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'E-mail 1': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['str_email2'] = makeSafe($_REQUEST['str_email2']);
		if($data['str_email2'] == empty_lookup_value){ $data['str_email2'] = ''; }
	$data['str_telefone1'] = makeSafe($_REQUEST['str_telefone1']);
		if($data['str_telefone1'] == empty_lookup_value){ $data['str_telefone1'] = ''; }
	$data['str_telefone2'] = makeSafe($_REQUEST['str_telefone2']);
		if($data['str_telefone2'] == empty_lookup_value){ $data['str_telefone2'] = ''; }
	$data['str_telefone3'] = makeSafe($_REQUEST['str_telefone3']);
		if($data['str_telefone3'] == empty_lookup_value){ $data['str_telefone3'] = ''; }
	$data['cidade'] = makeSafe($_REQUEST['cidade']);
		if($data['cidade'] == empty_lookup_value){ $data['cidade'] = ''; }
	$data['uf'] = makeSafe($_REQUEST['uf']);
		if($data['uf'] == empty_lookup_value){ $data['uf'] = ''; }
	$data['dta_cadastro'] = parseMySQLDate('', '<%%creationDate%%>');
	$data['selectedID']=makeSafe($selected_id);

	// hook: tb_contato_before_update
	if(function_exists('tb_contato_before_update')){
		$args=array();
		if(!tb_contato_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `tb_contato` set       `empresa_id`=' . (($data['empresa_id'] !== '' && $data['empresa_id'] !== NULL) ? "'{$data['empresa_id']}'" : 'NULL') . ', `str_primeiro_nome`=' . (($data['str_primeiro_nome'] !== '' && $data['str_primeiro_nome'] !== NULL) ? "'{$data['str_primeiro_nome']}'" : 'NULL') . ', `str_sobrenome`=' . (($data['str_sobrenome'] !== '' && $data['str_sobrenome'] !== NULL) ? "'{$data['str_sobrenome']}'" : 'NULL') . ', `str_nivel`=' . (($data['str_nivel'] !== '' && $data['str_nivel'] !== NULL) ? "'{$data['str_nivel']}'" : 'NULL') . ', `tipo_id`=' . (($data['tipo_id'] !== '' && $data['tipo_id'] !== NULL) ? "'{$data['tipo_id']}'" : 'NULL') . ', `str_email1`=' . (($data['str_email1'] !== '' && $data['str_email1'] !== NULL) ? "'{$data['str_email1']}'" : 'NULL') . ', `str_email2`=' . (($data['str_email2'] !== '' && $data['str_email2'] !== NULL) ? "'{$data['str_email2']}'" : 'NULL') . ', `str_telefone1`=' . (($data['str_telefone1'] !== '' && $data['str_telefone1'] !== NULL) ? "'{$data['str_telefone1']}'" : 'NULL') . ', `str_telefone2`=' . (($data['str_telefone2'] !== '' && $data['str_telefone2'] !== NULL) ? "'{$data['str_telefone2']}'" : 'NULL') . ', `str_telefone3`=' . (($data['str_telefone3'] !== '' && $data['str_telefone3'] !== NULL) ? "'{$data['str_telefone3']}'" : 'NULL') . ', `cidade`=' . (($data['cidade'] !== '' && $data['cidade'] !== NULL) ? "'{$data['cidade']}'" : 'NULL') . ', `uf`=' . (($data['uf'] !== '' && $data['uf'] !== NULL) ? "'{$data['uf']}'" : 'NULL') . ', `dta_cadastro`=`dta_cadastro`' . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="tb_contato_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: tb_contato_after_update
	if(function_exists('tb_contato_after_update')){
		$res = sql("SELECT * FROM `tb_contato` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!tb_contato_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='tb_contato' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function tb_contato_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('tb_contato');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_empresa_id = thisOr(undo_magic_quotes($_REQUEST['filterer_empresa_id']), '');
	$filterer_tipo_id = thisOr(undo_magic_quotes($_REQUEST['filterer_tipo_id']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: empresa_id
	$combo_empresa_id = new DataCombo;
	// combobox: str_nivel
	$combo_str_nivel = new Combo;
	$combo_str_nivel->ListType = 0;
	$combo_str_nivel->MultipleSeparator = ', ';
	$combo_str_nivel->ListBoxHeight = 10;
	$combo_str_nivel->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/tb_contato.str_nivel.csv')){
		$str_nivel_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/tb_contato.str_nivel.csv')));
		$combo_str_nivel->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($str_nivel_data)));
		$combo_str_nivel->ListData = $combo_str_nivel->ListItem;
	}else{
		$combo_str_nivel->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("ESTAGI&#193;RIO;;ASSISTENTE;;ANALISTA;;CONSULTOR;;COORDENADOR;;GERENTE;;DIRETOR")));
		$combo_str_nivel->ListData = $combo_str_nivel->ListItem;
	}
	$combo_str_nivel->SelectName = 'str_nivel';
	$combo_str_nivel->AllowNull = false;
	// combobox: tipo_id
	$combo_tipo_id = new DataCombo;
	// combobox: dta_cadastro
	$combo_dta_cadastro = new DateCombo;
	$combo_dta_cadastro->DateFormat = "dmy";
	$combo_dta_cadastro->MinYear = 1900;
	$combo_dta_cadastro->MaxYear = 2100;
	$combo_dta_cadastro->DefaultDate = parseMySQLDate('<%%creationDate%%>', '<%%creationDate%%>');
	$combo_dta_cadastro->MonthNames = $Translation['month names'];
	$combo_dta_cadastro->NamePrefix = 'dta_cadastro';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tb_contato' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tb_contato' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `tb_contato` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'tb_contato_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_empresa_id->SelectedData = $row['empresa_id'];
		$combo_str_nivel->SelectedData = $row['str_nivel'];
		$combo_tipo_id->SelectedData = $row['tipo_id'];
		$combo_dta_cadastro->DefaultDate = $row['dta_cadastro'];
	}else{
		$combo_empresa_id->SelectedData = $filterer_empresa_id;
		$combo_str_nivel->SelectedText = ( $_REQUEST['FilterField'][1]=='5' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_tipo_id->SelectedData = $filterer_tipo_id;
	}
	$combo_empresa_id->HTML = '<span id="empresa_id-container' . $rnd1 . '"></span><input type="hidden" name="empresa_id" id="empresa_id' . $rnd1 . '" value="' . html_attr($combo_empresa_id->SelectedData) . '">';
	$combo_empresa_id->MatchText = '<span id="empresa_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="empresa_id" id="empresa_id' . $rnd1 . '" value="' . html_attr($combo_empresa_id->SelectedData) . '">';
	$combo_str_nivel->Render();
	$combo_tipo_id->HTML = $combo_tipo_id->MatchText = '<span id="tipo_id-container' . $rnd1 . '"></span>';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_empresa_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['empresa_id'] : $filterer_empresa_id); ?>"};
		AppGini.current_tipo_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['tipo_id'] : $filterer_tipo_id); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(empresa_id_reload__RAND__) == 'function') empresa_id_reload__RAND__();
				if(typeof(tipo_id_reload__RAND__) == 'function') tipo_id_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function empresa_id_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#empresa_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_empresa_id__RAND__.value, t: 'tb_contato', f: 'empresa_id' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="empresa_id"]').val(resp.results[0].id);
							$j('[id=empresa_id-container-readonly__RAND__]').html('<span id="empresa_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_empresa_view_parent]').hide(); }else{ $j('.btn[id=tb_empresa_view_parent]').show(); }


							if(typeof(empresa_id_update_autofills__RAND__) == 'function') empresa_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'tb_contato', f: 'empresa_id' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_empresa_id__RAND__.value = e.added.id;
				AppGini.current_empresa_id__RAND__.text = e.added.text;
				$j('[name="empresa_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_empresa_view_parent]').hide(); }else{ $j('.btn[id=tb_empresa_view_parent]').show(); }


				if(typeof(empresa_id_update_autofills__RAND__) == 'function') empresa_id_update_autofills__RAND__();
			});

			if(!$j("#empresa_id-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_empresa_id__RAND__.value, t: 'tb_contato', f: 'empresa_id' },
					success: function(resp){
						$j('[name="empresa_id"]').val(resp.results[0].id);
						$j('[id=empresa_id-container-readonly__RAND__]').html('<span id="empresa_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_empresa_view_parent]').hide(); }else{ $j('.btn[id=tb_empresa_view_parent]').show(); }

						if(typeof(empresa_id_update_autofills__RAND__) == 'function') empresa_id_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_empresa_id__RAND__.value, t: 'tb_contato', f: 'empresa_id' },
				success: function(resp){
					$j('[id=empresa_id-container__RAND__], [id=empresa_id-container-readonly__RAND__]').html('<span id="empresa_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_empresa_view_parent]').hide(); }else{ $j('.btn[id=tb_empresa_view_parent]').show(); }

					if(typeof(empresa_id_update_autofills__RAND__) == 'function') empresa_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function tipo_id_reload__RAND__(){
			new Ajax.Updater("tipo_id-container__RAND__", "ajax_combo.php", {
				parameters: { t: "tb_contato", f: "tipo_id", id: AppGini.current_tipo_id__RAND__.value, text: AppGini.current_tipo_id__RAND__.text, o: <?php echo (($AllowUpdate || $AllowInsert) && !$dvprint ? '1' : '0'); ?> },
				method: "get",
				encoding: "<?php echo datalist_db_encoding; ?>",
				evalScripts: true,
				onComplete: function(){ /* */ tipo_id_changed__RAND__(); }
			});
		}
		function tipo_id_changed__RAND__(){
			if($j("input[name=tipo_id]").length){
				if($j("input[name=tipo_id]:checked").length){
					AppGini.current_tipo_id__RAND__.value = $j("input[name=tipo_id]:checked").val();
					AppGini.current_tipo_id__RAND__.text = "";
				}else{
					AppGini.current_tipo_id__RAND__.value = "";
					AppGini.current_tipo_id__RAND__.text = "";
				}
				AppGini.hideViewParentLinks();
			}

			if(typeof(tipo_id_update_autofills__RAND__) == 'function') tipo_id_update_autofills__RAND__();
		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/tb_contato_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/tb_contato_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalhes do contato', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm[1] && !$selected_id){ // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return tb_contato_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return tb_contato_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return tb_contato_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#empresa_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#empresa_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#str_primeiro_nome').replaceWith('<div class=\"form-control-static\" id=\"str_primeiro_nome\">' + (jQuery('#str_primeiro_nome').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#str_sobrenome').replaceWith('<div class=\"form-control-static\" id=\"str_sobrenome\">' + (jQuery('#str_sobrenome').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#str_nivel').replaceWith('<div class=\"form-control-static\" id=\"str_nivel\">' + (jQuery('#str_nivel').val() || '') + '</div>'); jQuery('#str_nivel-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#tipo_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#tipo_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#str_email1').replaceWith('<div class=\"form-control-static\" id=\"str_email1\">' + (jQuery('#str_email1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#str_email2').replaceWith('<div class=\"form-control-static\" id=\"str_email2\">' + (jQuery('#str_email2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#str_telefone1').replaceWith('<div class=\"form-control-static\" id=\"str_telefone1\">' + (jQuery('#str_telefone1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#str_telefone2').replaceWith('<div class=\"form-control-static\" id=\"str_telefone2\">' + (jQuery('#str_telefone2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#str_telefone3').replaceWith('<div class=\"form-control-static\" id=\"str_telefone3\">' + (jQuery('#str_telefone3').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#cidade').replaceWith('<div class=\"form-control-static\" id=\"cidade\">' + (jQuery('#cidade').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#uf').replaceWith('<div class=\"form-control-static\" id=\"uf\">' + (jQuery('#uf').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(empresa_id)%%>', $combo_empresa_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(empresa_id)%%>', $combo_empresa_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(empresa_id)%%>', urlencode($combo_empresa_id->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(str_nivel)%%>', $combo_str_nivel->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(str_nivel)%%>', $combo_str_nivel->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(tipo_id)%%>', $combo_tipo_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(tipo_id)%%>', $combo_tipo_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(tipo_id)%%>', urlencode($combo_tipo_id->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(dta_cadastro)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_dta_cadastro->GetHTML(true) . '</div>' : $combo_dta_cadastro->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(dta_cadastro)%%>', $combo_dta_cadastro->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'empresa_id' => array('tb_empresa', 'Empresa'), 'tipo_id' => array('tb_contato_tipo', 'Relacionamento'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(empresa_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(str_primeiro_nome)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(str_sobrenome)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(str_nivel)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tipo_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(str_email1)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(str_email2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(str_telefone1)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(str_telefone2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(str_telefone3)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(cidade)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(uf)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(dta_cadastro)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(empresa_id)%%>', safe_html($urow['empresa_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(empresa_id)%%>', html_attr($row['empresa_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(empresa_id)%%>', urlencode($urow['empresa_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(str_primeiro_nome)%%>', safe_html($urow['str_primeiro_nome']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(str_primeiro_nome)%%>', html_attr($row['str_primeiro_nome']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_primeiro_nome)%%>', urlencode($urow['str_primeiro_nome']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(str_sobrenome)%%>', safe_html($urow['str_sobrenome']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(str_sobrenome)%%>', html_attr($row['str_sobrenome']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_sobrenome)%%>', urlencode($urow['str_sobrenome']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(str_nivel)%%>', safe_html($urow['str_nivel']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(str_nivel)%%>', html_attr($row['str_nivel']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_nivel)%%>', urlencode($urow['str_nivel']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tipo_id)%%>', safe_html($urow['tipo_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tipo_id)%%>', html_attr($row['tipo_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipo_id)%%>', urlencode($urow['tipo_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(str_email1)%%>', safe_html($urow['str_email1']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(str_email1)%%>', html_attr($row['str_email1']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_email1)%%>', urlencode($urow['str_email1']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(str_email2)%%>', safe_html($urow['str_email2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(str_email2)%%>', html_attr($row['str_email2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_email2)%%>', urlencode($urow['str_email2']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(str_telefone1)%%>', safe_html($urow['str_telefone1']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(str_telefone1)%%>', html_attr($row['str_telefone1']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_telefone1)%%>', urlencode($urow['str_telefone1']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(str_telefone2)%%>', safe_html($urow['str_telefone2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(str_telefone2)%%>', html_attr($row['str_telefone2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_telefone2)%%>', urlencode($urow['str_telefone2']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(str_telefone3)%%>', safe_html($urow['str_telefone3']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(str_telefone3)%%>', html_attr($row['str_telefone3']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_telefone3)%%>', urlencode($urow['str_telefone3']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(cidade)%%>', safe_html($urow['cidade']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(cidade)%%>', html_attr($row['cidade']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cidade)%%>', urlencode($urow['cidade']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(uf)%%>', safe_html($urow['uf']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(uf)%%>', html_attr($row['uf']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(uf)%%>', urlencode($urow['uf']), $templateCode);
		$templateCode = str_replace('<%%VALUE(dta_cadastro)%%>', @date('d/m/Y', @strtotime(html_attr($row['dta_cadastro']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(dta_cadastro)%%>', urlencode(@date('d/m/Y', @strtotime(html_attr($urow['dta_cadastro'])))), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(empresa_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(empresa_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(str_primeiro_nome)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_primeiro_nome)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(str_sobrenome)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_sobrenome)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(str_nivel)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_nivel)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(tipo_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipo_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(str_email1)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_email1)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(str_email2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_email2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(str_telefone1)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_telefone1)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(str_telefone2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_telefone2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(str_telefone3)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_telefone3)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(cidade)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cidade)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(uf)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(uf)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(dta_cadastro)%%>', '<%%creationDate%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(dta_cadastro)%%>', urlencode('<%%creationDate%%>'), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('tb_contato');
	if($selected_id){
		$jdata = get_joined_record('tb_contato', $selected_id);
		if($jdata === false) $jdata = get_defaults('tb_contato');
		$rdata = $row;
	}
	$templateCode .= loadView('tb_contato-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: tb_contato_dv
	if(function_exists('tb_contato_dv')){
		$args=array();
		tb_contato_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>