<?php

// Data functions (insert, update, delete, form) for table tb_campanha_contato

// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

function tb_campanha_contato_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('tb_campanha_contato');
	if(!$arrPerm[1]){
		return false;
	}

	$data['campanha_id'] = makeSafe($_REQUEST['campanha_id']);
		if($data['campanha_id'] == empty_lookup_value){ $data['campanha_id'] = ''; }
	$data['empresa_id'] = makeSafe($_REQUEST['empresa_id']);
		if($data['empresa_id'] == empty_lookup_value){ $data['empresa_id'] = ''; }
	$data['contato_id'] = makeSafe($_REQUEST['contato_id']);
		if($data['contato_id'] == empty_lookup_value){ $data['contato_id'] = ''; }
	if($data['campanha_id']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Campanha': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['empresa_id']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Empresa': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['contato_id']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Contato': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: tb_campanha_contato_before_insert
	if(function_exists('tb_campanha_contato_before_insert')){
		$args=array();
		if(!tb_campanha_contato_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `tb_campanha_contato` set       `campanha_id`=' . (($data['campanha_id'] !== '' && $data['campanha_id'] !== NULL) ? "'{$data['campanha_id']}'" : 'NULL') . ', `empresa_id`=' . (($data['empresa_id'] !== '' && $data['empresa_id'] !== NULL) ? "'{$data['empresa_id']}'" : 'NULL') . ', `contato_id`=' . (($data['contato_id'] !== '' && $data['contato_id'] !== NULL) ? "'{$data['contato_id']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"tb_campanha_contato_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: tb_campanha_contato_after_insert
	if(function_exists('tb_campanha_contato_after_insert')){
		$res = sql("select * from `tb_campanha_contato` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!tb_campanha_contato_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('tb_campanha_contato', $recID, getLoggedMemberID());

	return $recID;
}

function tb_campanha_contato_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('tb_campanha_contato');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tb_campanha_contato' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tb_campanha_contato' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: tb_campanha_contato_before_delete
	if(function_exists('tb_campanha_contato_before_delete')){
		$args=array();
		if(!tb_campanha_contato_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `tb_campanha_contato` where `id`='$selected_id'", $eo);

	// hook: tb_campanha_contato_after_delete
	if(function_exists('tb_campanha_contato_after_delete')){
		$args=array();
		tb_campanha_contato_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='tb_campanha_contato' and pkValue='$selected_id'", $eo);
}

function tb_campanha_contato_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('tb_campanha_contato');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tb_campanha_contato' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tb_campanha_contato' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['campanha_id'] = makeSafe($_REQUEST['campanha_id']);
		if($data['campanha_id'] == empty_lookup_value){ $data['campanha_id'] = ''; }
	if($data['campanha_id']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Campanha': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['empresa_id'] = makeSafe($_REQUEST['empresa_id']);
		if($data['empresa_id'] == empty_lookup_value){ $data['empresa_id'] = ''; }
	if($data['empresa_id']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Empresa': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['contato_id'] = makeSafe($_REQUEST['contato_id']);
		if($data['contato_id'] == empty_lookup_value){ $data['contato_id'] = ''; }
	if($data['contato_id']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Contato': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['selectedID']=makeSafe($selected_id);

	// hook: tb_campanha_contato_before_update
	if(function_exists('tb_campanha_contato_before_update')){
		$args=array();
		if(!tb_campanha_contato_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `tb_campanha_contato` set       `campanha_id`=' . (($data['campanha_id'] !== '' && $data['campanha_id'] !== NULL) ? "'{$data['campanha_id']}'" : 'NULL') . ', `empresa_id`=' . (($data['empresa_id'] !== '' && $data['empresa_id'] !== NULL) ? "'{$data['empresa_id']}'" : 'NULL') . ', `contato_id`=' . (($data['contato_id'] !== '' && $data['contato_id'] !== NULL) ? "'{$data['contato_id']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="tb_campanha_contato_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: tb_campanha_contato_after_update
	if(function_exists('tb_campanha_contato_after_update')){
		$res = sql("SELECT * FROM `tb_campanha_contato` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!tb_campanha_contato_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='tb_campanha_contato' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function tb_campanha_contato_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('tb_campanha_contato');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_campanha_id = thisOr(undo_magic_quotes($_REQUEST['filterer_campanha_id']), '');
	$filterer_empresa_id = thisOr(undo_magic_quotes($_REQUEST['filterer_empresa_id']), '');
	$filterer_contato_id = thisOr(undo_magic_quotes($_REQUEST['filterer_contato_id']), '');

	// populate filterers, starting from children to grand-parents
	if($filterer_contato_id && !$filterer_empresa_id) $filterer_empresa_id = sqlValue("select empresa_id from tb_contato where id='" . makeSafe($filterer_contato_id) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: campanha_id
	$combo_campanha_id = new DataCombo;
	// combobox: empresa_id
	$combo_empresa_id = new DataCombo;
	// combobox: contato_id, filterable by: empresa_id
	$combo_contato_id = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tb_campanha_contato' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tb_campanha_contato' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `tb_campanha_contato` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'tb_campanha_contato_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_campanha_id->SelectedData = $row['campanha_id'];
		$combo_empresa_id->SelectedData = $row['empresa_id'];
		$combo_contato_id->SelectedData = $row['contato_id'];
	}else{
		$combo_campanha_id->SelectedData = $filterer_campanha_id;
		$combo_empresa_id->SelectedData = $filterer_empresa_id;
		$combo_contato_id->SelectedData = $filterer_contato_id;
	}
	$combo_campanha_id->HTML = '<span id="campanha_id-container' . $rnd1 . '"></span><input type="hidden" name="campanha_id" id="campanha_id' . $rnd1 . '" value="' . html_attr($combo_campanha_id->SelectedData) . '">';
	$combo_campanha_id->MatchText = '<span id="campanha_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="campanha_id" id="campanha_id' . $rnd1 . '" value="' . html_attr($combo_campanha_id->SelectedData) . '">';
	$combo_empresa_id->HTML = '<span id="empresa_id-container' . $rnd1 . '"></span><input type="hidden" name="empresa_id" id="empresa_id' . $rnd1 . '" value="' . html_attr($combo_empresa_id->SelectedData) . '">';
	$combo_empresa_id->MatchText = '<span id="empresa_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="empresa_id" id="empresa_id' . $rnd1 . '" value="' . html_attr($combo_empresa_id->SelectedData) . '">';
	$combo_contato_id->HTML = '<span id="contato_id-container' . $rnd1 . '"></span><input type="hidden" name="contato_id" id="contato_id' . $rnd1 . '" value="' . html_attr($combo_contato_id->SelectedData) . '">';
	$combo_contato_id->MatchText = '<span id="contato_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="contato_id" id="contato_id' . $rnd1 . '" value="' . html_attr($combo_contato_id->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_campanha_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['campanha_id'] : $filterer_campanha_id); ?>"};
		AppGini.current_empresa_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['empresa_id'] : $filterer_empresa_id); ?>"};
		AppGini.current_contato_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['contato_id'] : $filterer_contato_id); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(campanha_id_reload__RAND__) == 'function') campanha_id_reload__RAND__();
				if(typeof(empresa_id_reload__RAND__) == 'function') empresa_id_reload__RAND__();
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(contato_id_reload__RAND__) == \'function\') contato_id_reload__RAND__(AppGini.current_empresa_id__RAND__.value);' : ''); ?>
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function campanha_id_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#campanha_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_campanha_id__RAND__.value, t: 'tb_campanha_contato', f: 'campanha_id' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="campanha_id"]').val(resp.results[0].id);
							$j('[id=campanha_id-container-readonly__RAND__]').html('<span id="campanha_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_campanha_view_parent]').hide(); }else{ $j('.btn[id=tb_campanha_view_parent]').show(); }


							if(typeof(campanha_id_update_autofills__RAND__) == 'function') campanha_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'tb_campanha_contato', f: 'campanha_id' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_campanha_id__RAND__.value = e.added.id;
				AppGini.current_campanha_id__RAND__.text = e.added.text;
				$j('[name="campanha_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_campanha_view_parent]').hide(); }else{ $j('.btn[id=tb_campanha_view_parent]').show(); }


				if(typeof(campanha_id_update_autofills__RAND__) == 'function') campanha_id_update_autofills__RAND__();
			});

			if(!$j("#campanha_id-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_campanha_id__RAND__.value, t: 'tb_campanha_contato', f: 'campanha_id' },
					success: function(resp){
						$j('[name="campanha_id"]').val(resp.results[0].id);
						$j('[id=campanha_id-container-readonly__RAND__]').html('<span id="campanha_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_campanha_view_parent]').hide(); }else{ $j('.btn[id=tb_campanha_view_parent]').show(); }

						if(typeof(campanha_id_update_autofills__RAND__) == 'function') campanha_id_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_campanha_id__RAND__.value, t: 'tb_campanha_contato', f: 'campanha_id' },
				success: function(resp){
					$j('[id=campanha_id-container__RAND__], [id=campanha_id-container-readonly__RAND__]').html('<span id="campanha_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_campanha_view_parent]').hide(); }else{ $j('.btn[id=tb_campanha_view_parent]').show(); }

					if(typeof(campanha_id_update_autofills__RAND__) == 'function') campanha_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function empresa_id_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#empresa_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_empresa_id__RAND__.value, t: 'tb_campanha_contato', f: 'empresa_id' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="empresa_id"]').val(resp.results[0].id);
							$j('[id=empresa_id-container-readonly__RAND__]').html('<span id="empresa_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_empresa_view_parent]').hide(); }else{ $j('.btn[id=tb_empresa_view_parent]').show(); }

						if(typeof(contato_id_reload__RAND__) == 'function') contato_id_reload__RAND__(AppGini.current_empresa_id__RAND__.value);

							if(typeof(empresa_id_update_autofills__RAND__) == 'function') empresa_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'tb_campanha_contato', f: 'empresa_id' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_empresa_id__RAND__.value = e.added.id;
				AppGini.current_empresa_id__RAND__.text = e.added.text;
				$j('[name="empresa_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_empresa_view_parent]').hide(); }else{ $j('.btn[id=tb_empresa_view_parent]').show(); }

						if(typeof(contato_id_reload__RAND__) == 'function') contato_id_reload__RAND__(AppGini.current_empresa_id__RAND__.value);

				if(typeof(empresa_id_update_autofills__RAND__) == 'function') empresa_id_update_autofills__RAND__();
			});

			if(!$j("#empresa_id-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_empresa_id__RAND__.value, t: 'tb_campanha_contato', f: 'empresa_id' },
					success: function(resp){
						$j('[name="empresa_id"]').val(resp.results[0].id);
						$j('[id=empresa_id-container-readonly__RAND__]').html('<span id="empresa_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_empresa_view_parent]').hide(); }else{ $j('.btn[id=tb_empresa_view_parent]').show(); }

						if(typeof(empresa_id_update_autofills__RAND__) == 'function') empresa_id_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_empresa_id__RAND__.value, t: 'tb_campanha_contato', f: 'empresa_id' },
				success: function(resp){
					$j('[id=empresa_id-container__RAND__], [id=empresa_id-container-readonly__RAND__]').html('<span id="empresa_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_empresa_view_parent]').hide(); }else{ $j('.btn[id=tb_empresa_view_parent]').show(); }

					if(typeof(empresa_id_update_autofills__RAND__) == 'function') empresa_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function contato_id_reload__RAND__(filterer_empresa_id){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#contato_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_empresa_id: filterer_empresa_id, id: AppGini.current_contato_id__RAND__.value, t: 'tb_campanha_contato', f: 'contato_id' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="contato_id"]').val(resp.results[0].id);
							$j('[id=contato_id-container-readonly__RAND__]').html('<span id="contato_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_contato_view_parent]').hide(); }else{ $j('.btn[id=tb_contato_view_parent]').show(); }


							if(typeof(contato_id_update_autofills__RAND__) == 'function') contato_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { filterer_empresa_id: filterer_empresa_id, s: term, p: page, t: 'tb_campanha_contato', f: 'contato_id' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_contato_id__RAND__.value = e.added.id;
				AppGini.current_contato_id__RAND__.text = e.added.text;
				$j('[name="contato_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_contato_view_parent]').hide(); }else{ $j('.btn[id=tb_contato_view_parent]').show(); }


				if(typeof(contato_id_update_autofills__RAND__) == 'function') contato_id_update_autofills__RAND__();
			});

			if(!$j("#contato_id-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_contato_id__RAND__.value, t: 'tb_campanha_contato', f: 'contato_id' },
					success: function(resp){
						$j('[name="contato_id"]').val(resp.results[0].id);
						$j('[id=contato_id-container-readonly__RAND__]').html('<span id="contato_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_contato_view_parent]').hide(); }else{ $j('.btn[id=tb_contato_view_parent]').show(); }

						if(typeof(contato_id_update_autofills__RAND__) == 'function') contato_id_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_contato_id__RAND__.value, t: 'tb_campanha_contato', f: 'contato_id' },
				success: function(resp){
					$j('[id=contato_id-container__RAND__], [id=contato_id-container-readonly__RAND__]').html('<span id="contato_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_contato_view_parent]').hide(); }else{ $j('.btn[id=tb_contato_view_parent]').show(); }

					if(typeof(contato_id_update_autofills__RAND__) == 'function') contato_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	$templateCode = @file_get_contents('./templates/tb_campanha_contato_templateDV.html');

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalhes do contato da campanha', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return tb_campanha_contato_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return tb_campanha_contato_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return tb_campanha_contato_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#campanha_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#campanha_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#empresa_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#empresa_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#contato_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#contato_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(campanha_id)%%>', $combo_campanha_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(campanha_id)%%>', $combo_campanha_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(campanha_id)%%>', urlencode($combo_campanha_id->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(empresa_id)%%>', $combo_empresa_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(empresa_id)%%>', $combo_empresa_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(empresa_id)%%>', urlencode($combo_empresa_id->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(contato_id)%%>', $combo_contato_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(contato_id)%%>', $combo_contato_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(contato_id)%%>', urlencode($combo_contato_id->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'campanha_id' => array('tb_campanha', 'Campanha'), 'empresa_id' => array('tb_empresa', 'Empresa'), 'contato_id' => array('tb_contato', 'Contato'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(campanha_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(empresa_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(contato_id)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(campanha_id)%%>', safe_html($urow['campanha_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(campanha_id)%%>', html_attr($row['campanha_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(campanha_id)%%>', urlencode($urow['campanha_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(empresa_id)%%>', safe_html($urow['empresa_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(empresa_id)%%>', html_attr($row['empresa_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(empresa_id)%%>', urlencode($urow['empresa_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(contato_id)%%>', safe_html($urow['contato_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(contato_id)%%>', html_attr($row['contato_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contato_id)%%>', urlencode($urow['contato_id']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(campanha_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(campanha_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(empresa_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(empresa_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(contato_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contato_id)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('tb_campanha_contato');
	if($selected_id){
		$jdata = get_joined_record('tb_campanha_contato', $selected_id);
		if($jdata === false) $jdata = get_defaults('tb_campanha_contato');
		$rdata = $row;
	}
	$templateCode .= loadView('tb_campanha_contato-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: tb_campanha_contato_dv
	if(function_exists('tb_campanha_contato_dv')){
		$args=array();
		tb_campanha_contato_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>