<?php

// Data functions (insert, update, delete, form) for table tb_empresa

// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

function tb_empresa_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('tb_empresa');
	if(!$arrPerm[1]){
		return false;
	}

	$data['str_nome_fantasia'] = makeSafe($_REQUEST['str_nome_fantasia']);
		if($data['str_nome_fantasia'] == empty_lookup_value){ $data['str_nome_fantasia'] = ''; }
	$data['str_responsavel'] = makeSafe($_REQUEST['str_responsavel']);
		if($data['str_responsavel'] == empty_lookup_value){ $data['str_responsavel'] = ''; }
	$data['relacionamento_id'] = makeSafe($_REQUEST['relacionamento_id']);
		if($data['relacionamento_id'] == empty_lookup_value){ $data['relacionamento_id'] = ''; }
	$data['cidade'] = makeSafe($_REQUEST['cidade']);
		if($data['cidade'] == empty_lookup_value){ $data['cidade'] = ''; }
	$data['uf'] = makeSafe($_REQUEST['uf']);
		if($data['uf'] == empty_lookup_value){ $data['uf'] = ''; }
	if($data['str_nome_fantasia']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Nome fantasia': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['str_responsavel']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Gerente da conta': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['relacionamento_id']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Relacionamento': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['uf']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'UF': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: tb_empresa_before_insert
	if(function_exists('tb_empresa_before_insert')){
		$args=array();
		if(!tb_empresa_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `tb_empresa` set       `str_nome_fantasia`=' . (($data['str_nome_fantasia'] !== '' && $data['str_nome_fantasia'] !== NULL) ? "'{$data['str_nome_fantasia']}'" : 'NULL') . ', `str_responsavel`=' . (($data['str_responsavel'] !== '' && $data['str_responsavel'] !== NULL) ? "'{$data['str_responsavel']}'" : 'NULL') . ', `relacionamento_id`=' . (($data['relacionamento_id'] !== '' && $data['relacionamento_id'] !== NULL) ? "'{$data['relacionamento_id']}'" : 'NULL') . ', `cidade`=' . (($data['cidade'] !== '' && $data['cidade'] !== NULL) ? "'{$data['cidade']}'" : 'NULL') . ', `uf`=' . (($data['uf'] !== '' && $data['uf'] !== NULL) ? "'{$data['uf']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"tb_empresa_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: tb_empresa_after_insert
	if(function_exists('tb_empresa_after_insert')){
		$res = sql("select * from `tb_empresa` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!tb_empresa_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('tb_empresa', $recID, getLoggedMemberID());

	return $recID;
}

function tb_empresa_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('tb_empresa');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tb_empresa' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tb_empresa' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: tb_empresa_before_delete
	if(function_exists('tb_empresa_before_delete')){
		$args=array();
		if(!tb_empresa_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: tb_vaga
	$res = sql("select `id` from `tb_empresa` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `tb_vaga` where `empresa_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_vaga", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_vaga", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: tb_entrevista
	$res = sql("select `id` from `tb_empresa` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `tb_entrevista` where `empresa_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_entrevista", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_entrevista", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: tb_alocacao
	$res = sql("select `id` from `tb_empresa` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `tb_alocacao` where `int_empresa`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_alocacao", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_alocacao", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: tb_contato
	$res = sql("select `id` from `tb_empresa` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `tb_contato` where `empresa_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_contato", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_contato", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: tb_oportunidade
	$res = sql("select `id` from `tb_empresa` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `tb_oportunidade` where `empresa_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_oportunidade", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_oportunidade", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: tb_atendimento
	$res = sql("select `id` from `tb_empresa` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `tb_atendimento` where `empresa_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_atendimento", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_atendimento", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: tb_acompanhamento
	$res = sql("select `id` from `tb_empresa` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `tb_acompanhamento` where `empresa_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_acompanhamento", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_acompanhamento", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: tb_contrato
	$res = sql("select `id` from `tb_empresa` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `tb_contrato` where `empresa_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_contrato", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_contrato", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: tb_campanha_contato
	$res = sql("select `id` from `tb_empresa` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `tb_campanha_contato` where `empresa_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_campanha_contato", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_campanha_contato", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: tb_fatura
	$res = sql("select `id` from `tb_empresa` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `tb_fatura` where `empresa_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_fatura", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tb_fatura", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tb_empresa_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `tb_empresa` where `id`='$selected_id'", $eo);

	// hook: tb_empresa_after_delete
	if(function_exists('tb_empresa_after_delete')){
		$args=array();
		tb_empresa_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='tb_empresa' and pkValue='$selected_id'", $eo);
}

function tb_empresa_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('tb_empresa');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tb_empresa' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tb_empresa' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['str_nome_fantasia'] = makeSafe($_REQUEST['str_nome_fantasia']);
		if($data['str_nome_fantasia'] == empty_lookup_value){ $data['str_nome_fantasia'] = ''; }
	if($data['str_nome_fantasia']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nome fantasia': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['str_responsavel'] = makeSafe($_REQUEST['str_responsavel']);
		if($data['str_responsavel'] == empty_lookup_value){ $data['str_responsavel'] = ''; }
	if($data['str_responsavel']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Gerente da conta': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['relacionamento_id'] = makeSafe($_REQUEST['relacionamento_id']);
		if($data['relacionamento_id'] == empty_lookup_value){ $data['relacionamento_id'] = ''; }
	if($data['relacionamento_id']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Relacionamento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['cidade'] = makeSafe($_REQUEST['cidade']);
		if($data['cidade'] == empty_lookup_value){ $data['cidade'] = ''; }
	$data['uf'] = makeSafe($_REQUEST['uf']);
		if($data['uf'] == empty_lookup_value){ $data['uf'] = ''; }
	if($data['uf']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'UF': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['selectedID']=makeSafe($selected_id);

	// hook: tb_empresa_before_update
	if(function_exists('tb_empresa_before_update')){
		$args=array();
		if(!tb_empresa_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `tb_empresa` set       `str_nome_fantasia`=' . (($data['str_nome_fantasia'] !== '' && $data['str_nome_fantasia'] !== NULL) ? "'{$data['str_nome_fantasia']}'" : 'NULL') . ', `str_responsavel`=' . (($data['str_responsavel'] !== '' && $data['str_responsavel'] !== NULL) ? "'{$data['str_responsavel']}'" : 'NULL') . ', `relacionamento_id`=' . (($data['relacionamento_id'] !== '' && $data['relacionamento_id'] !== NULL) ? "'{$data['relacionamento_id']}'" : 'NULL') . ', `cidade`=' . (($data['cidade'] !== '' && $data['cidade'] !== NULL) ? "'{$data['cidade']}'" : 'NULL') . ', `uf`=' . (($data['uf'] !== '' && $data['uf'] !== NULL) ? "'{$data['uf']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="tb_empresa_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: tb_empresa_after_update
	if(function_exists('tb_empresa_after_update')){
		$res = sql("SELECT * FROM `tb_empresa` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!tb_empresa_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='tb_empresa' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function tb_empresa_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('tb_empresa');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_str_responsavel = thisOr(undo_magic_quotes($_REQUEST['filterer_str_responsavel']), '');
	$filterer_relacionamento_id = thisOr(undo_magic_quotes($_REQUEST['filterer_relacionamento_id']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: str_responsavel
	$combo_str_responsavel = new DataCombo;
	// combobox: relacionamento_id
	$combo_relacionamento_id = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tb_empresa' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tb_empresa' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `tb_empresa` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'tb_empresa_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_str_responsavel->SelectedData = $row['str_responsavel'];
		$combo_relacionamento_id->SelectedData = $row['relacionamento_id'];
	}else{
		$combo_str_responsavel->SelectedData = $filterer_str_responsavel;
		$combo_relacionamento_id->SelectedData = $filterer_relacionamento_id;
	}
	$combo_str_responsavel->HTML = '<span id="str_responsavel-container' . $rnd1 . '"></span><input type="hidden" name="str_responsavel" id="str_responsavel' . $rnd1 . '" value="' . html_attr($combo_str_responsavel->SelectedData) . '">';
	$combo_str_responsavel->MatchText = '<span id="str_responsavel-container-readonly' . $rnd1 . '"></span><input type="hidden" name="str_responsavel" id="str_responsavel' . $rnd1 . '" value="' . html_attr($combo_str_responsavel->SelectedData) . '">';
	$combo_relacionamento_id->HTML = $combo_relacionamento_id->MatchText = '<span id="relacionamento_id-container' . $rnd1 . '"></span>';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_str_responsavel__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['str_responsavel'] : $filterer_str_responsavel); ?>"};
		AppGini.current_relacionamento_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['relacionamento_id'] : $filterer_relacionamento_id); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(str_responsavel_reload__RAND__) == 'function') str_responsavel_reload__RAND__();
				if(typeof(relacionamento_id_reload__RAND__) == 'function') relacionamento_id_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function str_responsavel_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#str_responsavel-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_str_responsavel__RAND__.value, t: 'tb_empresa', f: 'str_responsavel' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="str_responsavel"]').val(resp.results[0].id);
							$j('[id=str_responsavel-container-readonly__RAND__]').html('<span id="str_responsavel-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_recrutador_view_parent]').hide(); }else{ $j('.btn[id=tb_recrutador_view_parent]').show(); }


							if(typeof(str_responsavel_update_autofills__RAND__) == 'function') str_responsavel_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'tb_empresa', f: 'str_responsavel' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_str_responsavel__RAND__.value = e.added.id;
				AppGini.current_str_responsavel__RAND__.text = e.added.text;
				$j('[name="str_responsavel"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_recrutador_view_parent]').hide(); }else{ $j('.btn[id=tb_recrutador_view_parent]').show(); }


				if(typeof(str_responsavel_update_autofills__RAND__) == 'function') str_responsavel_update_autofills__RAND__();
			});

			if(!$j("#str_responsavel-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_str_responsavel__RAND__.value, t: 'tb_empresa', f: 'str_responsavel' },
					success: function(resp){
						$j('[name="str_responsavel"]').val(resp.results[0].id);
						$j('[id=str_responsavel-container-readonly__RAND__]').html('<span id="str_responsavel-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_recrutador_view_parent]').hide(); }else{ $j('.btn[id=tb_recrutador_view_parent]').show(); }

						if(typeof(str_responsavel_update_autofills__RAND__) == 'function') str_responsavel_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_str_responsavel__RAND__.value, t: 'tb_empresa', f: 'str_responsavel' },
				success: function(resp){
					$j('[id=str_responsavel-container__RAND__], [id=str_responsavel-container-readonly__RAND__]').html('<span id="str_responsavel-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=tb_recrutador_view_parent]').hide(); }else{ $j('.btn[id=tb_recrutador_view_parent]').show(); }

					if(typeof(str_responsavel_update_autofills__RAND__) == 'function') str_responsavel_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function relacionamento_id_reload__RAND__(){
			new Ajax.Updater("relacionamento_id-container__RAND__", "ajax_combo.php", {
				parameters: { t: "tb_empresa", f: "relacionamento_id", id: AppGini.current_relacionamento_id__RAND__.value, text: AppGini.current_relacionamento_id__RAND__.text, o: <?php echo (($AllowUpdate || $AllowInsert) && !$dvprint ? '1' : '0'); ?> },
				method: "get",
				encoding: "<?php echo datalist_db_encoding; ?>",
				evalScripts: true,
				onComplete: function(){ /* */ relacionamento_id_changed__RAND__(); }
			});
		}
		function relacionamento_id_changed__RAND__(){
			if($j("input[name=relacionamento_id]").length){
				if($j("input[name=relacionamento_id]:checked").length){
					AppGini.current_relacionamento_id__RAND__.value = $j("input[name=relacionamento_id]:checked").val();
					AppGini.current_relacionamento_id__RAND__.text = "";
				}else{
					AppGini.current_relacionamento_id__RAND__.value = "";
					AppGini.current_relacionamento_id__RAND__.text = "";
				}
				AppGini.hideViewParentLinks();
			}

			if(typeof(relacionamento_id_update_autofills__RAND__) == 'function') relacionamento_id_update_autofills__RAND__();
		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/tb_empresa_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/tb_empresa_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalhes da empresa', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return tb_empresa_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return tb_empresa_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return tb_empresa_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#str_nome_fantasia').replaceWith('<div class=\"form-control-static\" id=\"str_nome_fantasia\">' + (jQuery('#str_nome_fantasia').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#str_responsavel').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#str_responsavel_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#relacionamento_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#relacionamento_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#cidade').replaceWith('<div class=\"form-control-static\" id=\"cidade\">' + (jQuery('#cidade').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#uf').replaceWith('<div class=\"form-control-static\" id=\"uf\">' + (jQuery('#uf').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(str_responsavel)%%>', $combo_str_responsavel->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(str_responsavel)%%>', $combo_str_responsavel->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(str_responsavel)%%>', urlencode($combo_str_responsavel->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(relacionamento_id)%%>', $combo_relacionamento_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(relacionamento_id)%%>', $combo_relacionamento_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(relacionamento_id)%%>', urlencode($combo_relacionamento_id->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'str_responsavel' => array('tb_recrutador', 'Gerente da conta'), 'relacionamento_id' => array('tb_contato_tipo', 'Relacionamento'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(str_nome_fantasia)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(str_responsavel)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(relacionamento_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(cidade)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(uf)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(str_nome_fantasia)%%>', safe_html($urow['str_nome_fantasia']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(str_nome_fantasia)%%>', html_attr($row['str_nome_fantasia']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_nome_fantasia)%%>', urlencode($urow['str_nome_fantasia']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(str_responsavel)%%>', safe_html($urow['str_responsavel']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(str_responsavel)%%>', html_attr($row['str_responsavel']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_responsavel)%%>', urlencode($urow['str_responsavel']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(relacionamento_id)%%>', safe_html($urow['relacionamento_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(relacionamento_id)%%>', html_attr($row['relacionamento_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(relacionamento_id)%%>', urlencode($urow['relacionamento_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(cidade)%%>', safe_html($urow['cidade']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(cidade)%%>', html_attr($row['cidade']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cidade)%%>', urlencode($urow['cidade']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(uf)%%>', safe_html($urow['uf']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(uf)%%>', html_attr($row['uf']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(uf)%%>', urlencode($urow['uf']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(str_nome_fantasia)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_nome_fantasia)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(str_responsavel)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(str_responsavel)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(relacionamento_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(relacionamento_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(cidade)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cidade)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(uf)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(uf)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('tb_empresa');
	if($selected_id){
		$jdata = get_joined_record('tb_empresa', $selected_id);
		if($jdata === false) $jdata = get_defaults('tb_empresa');
		$rdata = $row;
	}
	$templateCode .= loadView('tb_empresa-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: tb_empresa_dv
	if(function_exists('tb_empresa_dv')){
		$args=array();
		tb_empresa_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>