<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/tb_indicador.php");
	include("$currDir/tb_indicador_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('tb_indicador');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "tb_indicador";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`tb_indicador`.`id`" => "id",
		"`tb_indicador`.`str_departamento`" => "str_departamento",
		"`tb_indicador`.`str_nome`" => "str_nome",
		"`tb_indicador`.`str_descricao`" => "str_descricao",
		"`tb_indicador`.`str_unidade_medida`" => "str_unidade_medida"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`tb_indicador`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`tb_indicador`.`id`" => "id",
		"`tb_indicador`.`str_departamento`" => "str_departamento",
		"`tb_indicador`.`str_nome`" => "str_nome",
		"`tb_indicador`.`str_descricao`" => "str_descricao",
		"`tb_indicador`.`str_unidade_medida`" => "str_unidade_medida"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`tb_indicador`.`id`" => "ID",
		"`tb_indicador`.`str_departamento`" => "Departamento",
		"`tb_indicador`.`str_nome`" => "Nome do Indicador",
		"`tb_indicador`.`str_descricao`" => "Descri&#231;&#227;o",
		"`tb_indicador`.`str_unidade_medida`" => "Unidade de medida"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`tb_indicador`.`id`" => "id",
		"`tb_indicador`.`str_departamento`" => "str_departamento",
		"`tb_indicador`.`str_nome`" => "str_nome",
		"`tb_indicador`.`str_descricao`" => "str_descricao",
		"`tb_indicador`.`str_unidade_medida`" => "str_unidade_medida"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`tb_indicador` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "tb_indicador_view.php";
	$x->RedirectAfterInsert = "tb_indicador_view.php?SelectedID=#ID#";
	$x->TableTitle = "Metas e Indicadores";
	$x->TableIcon = "resources/table_icons/chart_up_color.png";
	$x->PrimaryKey = "`tb_indicador`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150);
	$x->ColCaption = array("Departamento", "Nome do Indicador", "Descri&#231;&#227;o", "Unidade de medida");
	$x->ColFieldName = array('str_departamento', 'str_nome', 'str_descricao', 'str_unidade_medida');
	$x->ColNumber  = array(2, 3, 4, 5);

	// template paths below are based on the app main directory
	$x->Template = 'templates/tb_indicador_templateTV.html';
	$x->SelectedTemplate = 'templates/tb_indicador_templateTVS.html';
	$x->TemplateDV = 'templates/tb_indicador_templateDV.html';
	$x->TemplateDVP = 'templates/tb_indicador_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tb_indicador`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='tb_indicador' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tb_indicador`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='tb_indicador' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`tb_indicador`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: tb_indicador_init
	$render=TRUE;
	if(function_exists('tb_indicador_init')){
		$args=array();
		$render=tb_indicador_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tb_indicador_header
	$headerCode='';
	if(function_exists('tb_indicador_header')){
		$args=array();
		$headerCode=tb_indicador_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: tb_indicador_footer
	$footerCode='';
	if(function_exists('tb_indicador_footer')){
		$args=array();
		$footerCode=tb_indicador_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>