<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/tb_indicador_periodo.php");
	include("$currDir/tb_indicador_periodo_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('tb_indicador_periodo');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "tb_indicador_periodo";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`tb_indicador_periodo`.`id`" => "id",
		"IF(    CHAR_LENGTH(`tb_indicador1`.`str_departamento`) || CHAR_LENGTH(`tb_indicador1`.`str_nome`), CONCAT_WS('',   `tb_indicador1`.`str_departamento`, ' - ', `tb_indicador1`.`str_nome`), '') /* Indicador */" => "indicador_id",
		"`tb_indicador_periodo`.`str_unidade`" => "str_unidade",
		"`tb_indicador_periodo`.`str_vertical`" => "str_vertical",
		"`tb_indicador_periodo`.`str_responsavel`" => "str_responsavel",
		"if(`tb_indicador_periodo`.`dta`,date_format(`tb_indicador_periodo`.`dta`,'%d/%m/%Y'),'')" => "dta",
		"`tb_indicador_periodo`.`flo_sazonalidade`" => "flo_sazonalidade",
		"`tb_indicador_periodo`.`int_meta`" => "int_meta",
		"`tb_indicador_periodo`.`int_meta_ajustada`" => "int_meta_ajustada",
		"`tb_indicador_periodo`.`int_realizado`" => "int_realizado"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`tb_indicador_periodo`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`tb_indicador_periodo`.`dta`',
		7 => '`tb_indicador_periodo`.`flo_sazonalidade`',
		8 => '`tb_indicador_periodo`.`int_meta`',
		9 => '`tb_indicador_periodo`.`int_meta_ajustada`',
		10 => '`tb_indicador_periodo`.`int_realizado`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`tb_indicador_periodo`.`id`" => "id",
		"IF(    CHAR_LENGTH(`tb_indicador1`.`str_departamento`) || CHAR_LENGTH(`tb_indicador1`.`str_nome`), CONCAT_WS('',   `tb_indicador1`.`str_departamento`, ' - ', `tb_indicador1`.`str_nome`), '') /* Indicador */" => "indicador_id",
		"`tb_indicador_periodo`.`str_unidade`" => "str_unidade",
		"`tb_indicador_periodo`.`str_vertical`" => "str_vertical",
		"`tb_indicador_periodo`.`str_responsavel`" => "str_responsavel",
		"if(`tb_indicador_periodo`.`dta`,date_format(`tb_indicador_periodo`.`dta`,'%d/%m/%Y'),'')" => "dta",
		"`tb_indicador_periodo`.`flo_sazonalidade`" => "flo_sazonalidade",
		"`tb_indicador_periodo`.`int_meta`" => "int_meta",
		"`tb_indicador_periodo`.`int_meta_ajustada`" => "int_meta_ajustada",
		"`tb_indicador_periodo`.`int_realizado`" => "int_realizado"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`tb_indicador_periodo`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`tb_indicador1`.`str_departamento`) || CHAR_LENGTH(`tb_indicador1`.`str_nome`), CONCAT_WS('',   `tb_indicador1`.`str_departamento`, ' - ', `tb_indicador1`.`str_nome`), '') /* Indicador */" => "Indicador",
		"`tb_indicador_periodo`.`str_unidade`" => "Unidade",
		"`tb_indicador_periodo`.`str_vertical`" => "Vertical",
		"`tb_indicador_periodo`.`str_responsavel`" => "Respons&#225;vel",
		"`tb_indicador_periodo`.`dta`" => "Data",
		"`tb_indicador_periodo`.`flo_sazonalidade`" => "Sazonalidade",
		"`tb_indicador_periodo`.`int_meta`" => "Meta",
		"`tb_indicador_periodo`.`int_meta_ajustada`" => "Meta ajustada",
		"`tb_indicador_periodo`.`int_realizado`" => "Realizado"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`tb_indicador_periodo`.`id`" => "id",
		"IF(    CHAR_LENGTH(`tb_indicador1`.`str_departamento`) || CHAR_LENGTH(`tb_indicador1`.`str_nome`), CONCAT_WS('',   `tb_indicador1`.`str_departamento`, ' - ', `tb_indicador1`.`str_nome`), '') /* Indicador */" => "indicador_id",
		"`tb_indicador_periodo`.`str_unidade`" => "str_unidade",
		"`tb_indicador_periodo`.`str_vertical`" => "str_vertical",
		"`tb_indicador_periodo`.`str_responsavel`" => "str_responsavel",
		"if(`tb_indicador_periodo`.`dta`,date_format(`tb_indicador_periodo`.`dta`,'%d/%m/%Y'),'')" => "dta",
		"`tb_indicador_periodo`.`flo_sazonalidade`" => "flo_sazonalidade",
		"`tb_indicador_periodo`.`int_meta`" => "int_meta",
		"`tb_indicador_periodo`.`int_meta_ajustada`" => "int_meta_ajustada",
		"`tb_indicador_periodo`.`int_realizado`" => "int_realizado"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'indicador_id' => 'Indicador');

	$x->QueryFrom = "`tb_indicador_periodo` LEFT JOIN `tb_indicador` as tb_indicador1 ON `tb_indicador1`.`id`=`tb_indicador_periodo`.`indicador_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "tb_indicador_periodo_view.php";
	$x->RedirectAfterInsert = "tb_indicador_periodo_view.php?SelectedID=#ID#";
	$x->TableTitle = "Per&#237;odos dos indicadores";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`tb_indicador_periodo`.`id`";
	$x->DefaultSortField = '`tb_indicador_periodo`.`dta`';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Indicador", "Unidade", "Vertical", "Respons&#225;vel", "Data", "Sazonalidade", "Meta", "Meta ajustada", "Realizado");
	$x->ColFieldName = array('indicador_id', 'str_unidade', 'str_vertical', 'str_responsavel', 'dta', 'flo_sazonalidade', 'int_meta', 'int_meta_ajustada', 'int_realizado');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10);

	// template paths below are based on the app main directory
	$x->Template = 'templates/tb_indicador_periodo_templateTV.html';
	$x->SelectedTemplate = 'templates/tb_indicador_periodo_templateTVS.html';
	$x->TemplateDV = 'templates/tb_indicador_periodo_templateDV.html';
	$x->TemplateDVP = 'templates/tb_indicador_periodo_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tb_indicador_periodo`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='tb_indicador_periodo' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tb_indicador_periodo`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='tb_indicador_periodo' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`tb_indicador_periodo`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: tb_indicador_periodo_init
	$render=TRUE;
	if(function_exists('tb_indicador_periodo_init')){
		$args=array();
		$render=tb_indicador_periodo_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tb_indicador_periodo_header
	$headerCode='';
	if(function_exists('tb_indicador_periodo_header')){
		$args=array();
		$headerCode=tb_indicador_periodo_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: tb_indicador_periodo_footer
	$footerCode='';
	if(function_exists('tb_indicador_periodo_footer')){
		$args=array();
		$footerCode=tb_indicador_periodo_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>